/*
 * This file is generated by jOOQ.
 */
package com.geoly.app.jooq;


import com.geoly.app.jooq.tables.Badge;
import com.geoly.app.jooq.tables.Category;
import com.geoly.app.jooq.tables.Image;
import com.geoly.app.jooq.tables.Language;
import com.geoly.app.jooq.tables.Log;
import com.geoly.app.jooq.tables.Notification;
import com.geoly.app.jooq.tables.Party;
import com.geoly.app.jooq.tables.PartyInvite;
import com.geoly.app.jooq.tables.PartyQuest;
import com.geoly.app.jooq.tables.PartyUser;
import com.geoly.app.jooq.tables.Point;
import com.geoly.app.jooq.tables.Premium;
import com.geoly.app.jooq.tables.Quest;
import com.geoly.app.jooq.tables.QuestReport;
import com.geoly.app.jooq.tables.QuestReview;
import com.geoly.app.jooq.tables.Role;
import com.geoly.app.jooq.tables.Sale;
import com.geoly.app.jooq.tables.Stage;
import com.geoly.app.jooq.tables.Token;
import com.geoly.app.jooq.tables.User;
import com.geoly.app.jooq.tables.UserBadge;
import com.geoly.app.jooq.tables.UserOption;
import com.geoly.app.jooq.tables.UserPartyQuest;
import com.geoly.app.jooq.tables.UserQuest;
import com.geoly.app.jooq.tables.UserReport;
import com.geoly.app.jooq.tables.UserRole;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Geoly extends SchemaImpl {

    private static final long serialVersionUID = -1579382643;

    /**
     * The reference instance of <code>geoly</code>
     */
    public static final Geoly GEOLY = new Geoly();

    /**
     * The table <code>geoly.BADGE</code>.
     */
    public final Badge BADGE = com.geoly.app.jooq.tables.Badge.BADGE;

    /**
     * The table <code>geoly.CATEGORY</code>.
     */
    public final Category CATEGORY = com.geoly.app.jooq.tables.Category.CATEGORY;

    /**
     * The table <code>geoly.IMAGE</code>.
     */
    public final Image IMAGE = com.geoly.app.jooq.tables.Image.IMAGE;

    /**
     * The table <code>geoly.LANGUAGE</code>.
     */
    public final Language LANGUAGE = com.geoly.app.jooq.tables.Language.LANGUAGE;

    /**
     * The table <code>geoly.LOG</code>.
     */
    public final Log LOG = com.geoly.app.jooq.tables.Log.LOG;

    /**
     * The table <code>geoly.NOTIFICATION</code>.
     */
    public final Notification NOTIFICATION = com.geoly.app.jooq.tables.Notification.NOTIFICATION;

    /**
     * The table <code>geoly.PARTY</code>.
     */
    public final Party PARTY = com.geoly.app.jooq.tables.Party.PARTY;

    /**
     * The table <code>geoly.PARTY_INVITE</code>.
     */
    public final PartyInvite PARTY_INVITE = com.geoly.app.jooq.tables.PartyInvite.PARTY_INVITE;

    /**
     * The table <code>geoly.PARTY_QUEST</code>.
     */
    public final PartyQuest PARTY_QUEST = com.geoly.app.jooq.tables.PartyQuest.PARTY_QUEST;

    /**
     * The table <code>geoly.PARTY_USER</code>.
     */
    public final PartyUser PARTY_USER = com.geoly.app.jooq.tables.PartyUser.PARTY_USER;

    /**
     * The table <code>geoly.POINT</code>.
     */
    public final Point POINT = com.geoly.app.jooq.tables.Point.POINT;

    /**
     * The table <code>geoly.PREMIUM</code>.
     */
    public final Premium PREMIUM = com.geoly.app.jooq.tables.Premium.PREMIUM;

    /**
     * The table <code>geoly.QUEST</code>.
     */
    public final Quest QUEST = com.geoly.app.jooq.tables.Quest.QUEST;

    /**
     * The table <code>geoly.QUEST_REPORT</code>.
     */
    public final QuestReport QUEST_REPORT = com.geoly.app.jooq.tables.QuestReport.QUEST_REPORT;

    /**
     * The table <code>geoly.QUEST_REVIEW</code>.
     */
    public final QuestReview QUEST_REVIEW = com.geoly.app.jooq.tables.QuestReview.QUEST_REVIEW;

    /**
     * The table <code>geoly.ROLE</code>.
     */
    public final Role ROLE = com.geoly.app.jooq.tables.Role.ROLE;

    /**
     * The table <code>geoly.SALE</code>.
     */
    public final Sale SALE = com.geoly.app.jooq.tables.Sale.SALE;

    /**
     * The table <code>geoly.STAGE</code>.
     */
    public final Stage STAGE = com.geoly.app.jooq.tables.Stage.STAGE;

    /**
     * The table <code>geoly.TOKEN</code>.
     */
    public final Token TOKEN = com.geoly.app.jooq.tables.Token.TOKEN;

    /**
     * The table <code>geoly.USER</code>.
     */
    public final User USER = com.geoly.app.jooq.tables.User.USER;

    /**
     * The table <code>geoly.USER_BADGE</code>.
     */
    public final UserBadge USER_BADGE = com.geoly.app.jooq.tables.UserBadge.USER_BADGE;

    /**
     * The table <code>geoly.USER_OPTION</code>.
     */
    public final UserOption USER_OPTION = com.geoly.app.jooq.tables.UserOption.USER_OPTION;

    /**
     * The table <code>geoly.USER_PARTY_QUEST</code>.
     */
    public final UserPartyQuest USER_PARTY_QUEST = com.geoly.app.jooq.tables.UserPartyQuest.USER_PARTY_QUEST;

    /**
     * The table <code>geoly.USER_QUEST</code>.
     */
    public final UserQuest USER_QUEST = com.geoly.app.jooq.tables.UserQuest.USER_QUEST;

    /**
     * The table <code>geoly.USER_REPORT</code>.
     */
    public final UserReport USER_REPORT = com.geoly.app.jooq.tables.UserReport.USER_REPORT;

    /**
     * The table <code>geoly.USER_ROLE</code>.
     */
    public final UserRole USER_ROLE = com.geoly.app.jooq.tables.UserRole.USER_ROLE;

    /**
     * No further instances allowed
     */
    private Geoly() {
        super("geoly", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.HIBERNATE_SEQUENCE);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Badge.BADGE,
            Category.CATEGORY,
            Image.IMAGE,
            Language.LANGUAGE,
            Log.LOG,
            Notification.NOTIFICATION,
            Party.PARTY,
            PartyInvite.PARTY_INVITE,
            PartyQuest.PARTY_QUEST,
            PartyUser.PARTY_USER,
            Point.POINT,
            Premium.PREMIUM,
            Quest.QUEST,
            QuestReport.QUEST_REPORT,
            QuestReview.QUEST_REVIEW,
            Role.ROLE,
            Sale.SALE,
            Stage.STAGE,
            Token.TOKEN,
            User.USER,
            UserBadge.USER_BADGE,
            UserOption.USER_OPTION,
            UserPartyQuest.USER_PARTY_QUEST,
            UserQuest.USER_QUEST,
            UserReport.USER_REPORT,
            UserRole.USER_ROLE);
    }
}
