/*
 * This file is generated by jOOQ.
 */
package com.geoly.app.jooq;


import com.geoly.app.jooq.tables.Badge;
import com.geoly.app.jooq.tables.Category;
import com.geoly.app.jooq.tables.Image;
import com.geoly.app.jooq.tables.Language;
import com.geoly.app.jooq.tables.Party;
import com.geoly.app.jooq.tables.PartyInvite;
import com.geoly.app.jooq.tables.PartyQuest;
import com.geoly.app.jooq.tables.PartyUser;
import com.geoly.app.jooq.tables.Point;
import com.geoly.app.jooq.tables.Premium;
import com.geoly.app.jooq.tables.Quest;
import com.geoly.app.jooq.tables.QuestReport;
import com.geoly.app.jooq.tables.QuestReview;
import com.geoly.app.jooq.tables.Role;
import com.geoly.app.jooq.tables.Sale;
import com.geoly.app.jooq.tables.Stage;
import com.geoly.app.jooq.tables.Token;
import com.geoly.app.jooq.tables.Transaction;
import com.geoly.app.jooq.tables.User;
import com.geoly.app.jooq.tables.UserBadge;
import com.geoly.app.jooq.tables.UserOption;
import com.geoly.app.jooq.tables.UserQuest;
import com.geoly.app.jooq.tables.UserReport;
import com.geoly.app.jooq.tables.UserRole;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>geoly</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index PRIMARY_KEY_3 = Indexes0.PRIMARY_KEY_3;
    public static final Index PRIMARY_KEY_31 = Indexes0.PRIMARY_KEY_31;
    public static final Index FK3N5NEGXV9EYM0STD2EUTTVG6W_INDEX_4 = Indexes0.FK3N5NEGXV9EYM0STD2EUTTVG6W_INDEX_4;
    public static final Index PRIMARY_KEY_4 = Indexes0.PRIMARY_KEY_4;
    public static final Index PRIMARY_KEY_C = Indexes0.PRIMARY_KEY_C;
    public static final Index FKTCAG4FSDQKMO7OWJKK1P25H41_INDEX_4 = Indexes0.FKTCAG4FSDQKMO7OWJKK1P25H41_INDEX_4;
    public static final Index PRIMARY_KEY_48 = Indexes0.PRIMARY_KEY_48;
    public static final Index FK5N5BG86WU1LEDOPG6IN964H6J_INDEX_5 = Indexes0.FK5N5BG86WU1LEDOPG6IN964H6J_INDEX_5;
    public static final Index FKG0D7MD7NQV6Y8UNXO7TFR722F_INDEX_5 = Indexes0.FKG0D7MD7NQV6Y8UNXO7TFR722F_INDEX_5;
    public static final Index PRIMARY_KEY_5 = Indexes0.PRIMARY_KEY_5;
    public static final Index FK2GIGO39GG9CLIMKUAALBB2OD0_INDEX_2 = Indexes0.FK2GIGO39GG9CLIMKUAALBB2OD0_INDEX_2;
    public static final Index FK8FL0NU8HGJ8JESC5HPWBIO1UB_INDEX_2 = Indexes0.FK8FL0NU8HGJ8JESC5HPWBIO1UB_INDEX_2;
    public static final Index PRIMARY_KEY_2 = Indexes0.PRIMARY_KEY_2;
    public static final Index FKGBM3CRUYQ6N25LRIIYC2XAD43_INDEX_3 = Indexes0.FKGBM3CRUYQ6N25LRIIYC2XAD43_INDEX_3;
    public static final Index FKOATBT6TV26KK2R5VGUA7OJSM_INDEX_3 = Indexes0.FKOATBT6TV26KK2R5VGUA7OJSM_INDEX_3;
    public static final Index PRIMARY_KEY_3B = Indexes0.PRIMARY_KEY_3B;
    public static final Index FKH4QXMN9MIG6KITH0ISH2R67KA_INDEX_4 = Indexes0.FKH4QXMN9MIG6KITH0ISH2R67KA_INDEX_4;
    public static final Index PRIMARY_KEY_48C = Indexes0.PRIMARY_KEY_48C;
    public static final Index FK55RHAW7HB4IB9USGJD0RVYUBB_INDEX_1 = Indexes0.FK55RHAW7HB4IB9USGJD0RVYUBB_INDEX_1;
    public static final Index FKOTOO6BVI30QYEL0RVHS8OH9WO_INDEX_1 = Indexes0.FKOTOO6BVI30QYEL0RVHS8OH9WO_INDEX_1;
    public static final Index PRIMARY_KEY_1 = Indexes0.PRIMARY_KEY_1;
    public static final Index FK4FOEBLYDMUA10QB2OEUANE6FB_INDEX_4 = Indexes0.FK4FOEBLYDMUA10QB2OEUANE6FB_INDEX_4;
    public static final Index FKLGSC5AJ1JQDFWJ8V3PKHBIDNX_INDEX_4 = Indexes0.FKLGSC5AJ1JQDFWJ8V3PKHBIDNX_INDEX_4;
    public static final Index PRIMARY_KEY_49 = Indexes0.PRIMARY_KEY_49;
    public static final Index FKJ20N6BQIYJ8MVBJWR5EXDH37T_INDEX_1 = Indexes0.FKJ20N6BQIYJ8MVBJWR5EXDH37T_INDEX_1;
    public static final Index FKODP2V6API3IL5GL748PXYPKWJ_INDEX_1 = Indexes0.FKODP2V6API3IL5GL748PXYPKWJ_INDEX_1;
    public static final Index PRIMARY_KEY_10 = Indexes0.PRIMARY_KEY_10;
    public static final Index FK1HJWWRR4XDDJJ9C7IICVVM78J_INDEX_1 = Indexes0.FK1HJWWRR4XDDJJ9C7IICVVM78J_INDEX_1;
    public static final Index FKQG1FBVCAVQ2LBPP8G8W8VTIAM_INDEX_1 = Indexes0.FKQG1FBVCAVQ2LBPP8G8W8VTIAM_INDEX_1;
    public static final Index PRIMARY_KEY_105 = Indexes0.PRIMARY_KEY_105;
    public static final Index PRIMARY_KEY_26 = Indexes0.PRIMARY_KEY_26;
    public static final Index PRIMARY_KEY_26B = Indexes0.PRIMARY_KEY_26B;
    public static final Index FKMUJKS4H5F77VK9X2HH1L4YPVG_INDEX_4 = Indexes0.FKMUJKS4H5F77VK9X2HH1L4YPVG_INDEX_4;
    public static final Index PRIMARY_KEY_4B = Indexes0.PRIMARY_KEY_4B;
    public static final Index FKE32EK7IXANAKFQSDAOKM4Q9Y2_INDEX_4 = Indexes0.FKE32EK7IXANAKFQSDAOKM4Q9Y2_INDEX_4;
    public static final Index PRIMARY_KEY_4C = Indexes0.PRIMARY_KEY_4C;
    public static final Index FKSG7JP0AJ6QIPR50856WF6VBW1_INDEX_F = Indexes0.FKSG7JP0AJ6QIPR50856WF6VBW1_INDEX_F;
    public static final Index PRIMARY_KEY_F = Indexes0.PRIMARY_KEY_F;
    public static final Index PRIMARY_KEY_27 = Indexes0.PRIMARY_KEY_27;
    public static final Index UK_D2IA11OQHSYNODBSI46M80VFC_INDEX_2 = Indexes0.UK_D2IA11OQHSYNODBSI46M80VFC_INDEX_2;
    public static final Index UK_OB8KQYQQGMEFL0ACO34AKDTPE_INDEX_2 = Indexes0.UK_OB8KQYQQGMEFL0ACO34AKDTPE_INDEX_2;
    public static final Index FK2JW9FPOTMMBDA07K27QC9T2UL_INDEX_C = Indexes0.FK2JW9FPOTMMBDA07K27QC9T2UL_INDEX_C;
    public static final Index FKJQX9N26PK9MQF1QO8F7XVVOQ9_INDEX_C = Indexes0.FKJQX9N26PK9MQF1QO8F7XVVOQ9_INDEX_C;
    public static final Index PRIMARY_KEY_C5 = Indexes0.PRIMARY_KEY_C5;
    public static final Index FK8USX5LQY3O113K7K4436XBERW_INDEX_D = Indexes0.FK8USX5LQY3O113K7K4436XBERW_INDEX_D;
    public static final Index FKR6EERMF5AQ2NUA7HSSPMFFG02_INDEX_D = Indexes0.FKR6EERMF5AQ2NUA7HSSPMFFG02_INDEX_D;
    public static final Index PRIMARY_KEY_D = Indexes0.PRIMARY_KEY_D;
    public static final Index FK8JDYAKV4ATARQD05U7AXUBMYK_INDEX_C = Indexes0.FK8JDYAKV4ATARQD05U7AXUBMYK_INDEX_C;
    public static final Index FKKMK9IF2IG0F3GQ6TTISKHIO7C_INDEX_C = Indexes0.FKKMK9IF2IG0F3GQ6TTISKHIO7C_INDEX_C;
    public static final Index PRIMARY_KEY_C6 = Indexes0.PRIMARY_KEY_C6;
    public static final Index FK2CM7CI55E41B6EAKUNXYDH3LG_INDEX_1 = Indexes0.FK2CM7CI55E41B6EAKUNXYDH3LG_INDEX_1;
    public static final Index FKO1LNULINQCBVABO3W4NI3K4D1_INDEX_1 = Indexes0.FKO1LNULINQCBVABO3W4NI3K4D1_INDEX_1;
    public static final Index PRIMARY_KEY_11 = Indexes0.PRIMARY_KEY_11;
    public static final Index FK859N2JVI8IVHUI0RL0ESWS6O_INDEX_B = Indexes0.FK859N2JVI8IVHUI0RL0ESWS6O_INDEX_B;
    public static final Index FKA68196081FVOVJHKEK5M97N3Y_INDEX_B = Indexes0.FKA68196081FVOVJHKEK5M97N3Y_INDEX_B;
    public static final Index PRIMARY_KEY_B = Indexes0.PRIMARY_KEY_B;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index PRIMARY_KEY_3 = Internal.createIndex("PRIMARY_KEY_3", Badge.BADGE, new OrderField[] { Badge.BADGE.ID }, true);
        public static Index PRIMARY_KEY_31 = Internal.createIndex("PRIMARY_KEY_31", Category.CATEGORY, new OrderField[] { Category.CATEGORY.ID }, true);
        public static Index FK3N5NEGXV9EYM0STD2EUTTVG6W_INDEX_4 = Internal.createIndex("FK3N5NEGXV9EYM0STD2EUTTVG6W_INDEX_4", Image.IMAGE, new OrderField[] { Image.IMAGE.QUEST_ID }, false);
        public static Index PRIMARY_KEY_4 = Internal.createIndex("PRIMARY_KEY_4", Image.IMAGE, new OrderField[] { Image.IMAGE.ID }, true);
        public static Index PRIMARY_KEY_C = Internal.createIndex("PRIMARY_KEY_C", Language.LANGUAGE, new OrderField[] { Language.LANGUAGE.ID }, true);
        public static Index FKTCAG4FSDQKMO7OWJKK1P25H41_INDEX_4 = Internal.createIndex("FKTCAG4FSDQKMO7OWJKK1P25H41_INDEX_4", Party.PARTY, new OrderField[] { Party.PARTY.USER_ID }, false);
        public static Index PRIMARY_KEY_48 = Internal.createIndex("PRIMARY_KEY_48", Party.PARTY, new OrderField[] { Party.PARTY.ID }, true);
        public static Index FK5N5BG86WU1LEDOPG6IN964H6J_INDEX_5 = Internal.createIndex("FK5N5BG86WU1LEDOPG6IN964H6J_INDEX_5", PartyInvite.PARTY_INVITE, new OrderField[] { PartyInvite.PARTY_INVITE.USER_ID }, false);
        public static Index FKG0D7MD7NQV6Y8UNXO7TFR722F_INDEX_5 = Internal.createIndex("FKG0D7MD7NQV6Y8UNXO7TFR722F_INDEX_5", PartyInvite.PARTY_INVITE, new OrderField[] { PartyInvite.PARTY_INVITE.PARTY_ID }, false);
        public static Index PRIMARY_KEY_5 = Internal.createIndex("PRIMARY_KEY_5", PartyInvite.PARTY_INVITE, new OrderField[] { PartyInvite.PARTY_INVITE.ID }, true);
        public static Index FK2GIGO39GG9CLIMKUAALBB2OD0_INDEX_2 = Internal.createIndex("FK2GIGO39GG9CLIMKUAALBB2OD0_INDEX_2", PartyQuest.PARTY_QUEST, new OrderField[] { PartyQuest.PARTY_QUEST.PARTY_ID }, false);
        public static Index FK8FL0NU8HGJ8JESC5HPWBIO1UB_INDEX_2 = Internal.createIndex("FK8FL0NU8HGJ8JESC5HPWBIO1UB_INDEX_2", PartyQuest.PARTY_QUEST, new OrderField[] { PartyQuest.PARTY_QUEST.QUEST_ID }, false);
        public static Index PRIMARY_KEY_2 = Internal.createIndex("PRIMARY_KEY_2", PartyQuest.PARTY_QUEST, new OrderField[] { PartyQuest.PARTY_QUEST.ID }, true);
        public static Index FKGBM3CRUYQ6N25LRIIYC2XAD43_INDEX_3 = Internal.createIndex("FKGBM3CRUYQ6N25LRIIYC2XAD43_INDEX_3", PartyUser.PARTY_USER, new OrderField[] { PartyUser.PARTY_USER.USER_ID }, false);
        public static Index FKOATBT6TV26KK2R5VGUA7OJSM_INDEX_3 = Internal.createIndex("FKOATBT6TV26KK2R5VGUA7OJSM_INDEX_3", PartyUser.PARTY_USER, new OrderField[] { PartyUser.PARTY_USER.PARTY_ID }, false);
        public static Index PRIMARY_KEY_3B = Internal.createIndex("PRIMARY_KEY_3B", PartyUser.PARTY_USER, new OrderField[] { PartyUser.PARTY_USER.ID }, true);
        public static Index FKH4QXMN9MIG6KITH0ISH2R67KA_INDEX_4 = Internal.createIndex("FKH4QXMN9MIG6KITH0ISH2R67KA_INDEX_4", Point.POINT, new OrderField[] { Point.POINT.USER_ID }, false);
        public static Index PRIMARY_KEY_48C = Internal.createIndex("PRIMARY_KEY_48C", Point.POINT, new OrderField[] { Point.POINT.ID }, true);
        public static Index FK55RHAW7HB4IB9USGJD0RVYUBB_INDEX_1 = Internal.createIndex("FK55RHAW7HB4IB9USGJD0RVYUBB_INDEX_1", Premium.PREMIUM, new OrderField[] { Premium.PREMIUM.USER_ID }, false);
        public static Index FKOTOO6BVI30QYEL0RVHS8OH9WO_INDEX_1 = Internal.createIndex("FKOTOO6BVI30QYEL0RVHS8OH9WO_INDEX_1", Premium.PREMIUM, new OrderField[] { Premium.PREMIUM.TRANSACTION_ID }, false);
        public static Index PRIMARY_KEY_1 = Internal.createIndex("PRIMARY_KEY_1", Premium.PREMIUM, new OrderField[] { Premium.PREMIUM.ID }, true);
        public static Index FK4FOEBLYDMUA10QB2OEUANE6FB_INDEX_4 = Internal.createIndex("FK4FOEBLYDMUA10QB2OEUANE6FB_INDEX_4", Quest.QUEST, new OrderField[] { Quest.QUEST.CATEGORY_ID }, false);
        public static Index FKLGSC5AJ1JQDFWJ8V3PKHBIDNX_INDEX_4 = Internal.createIndex("FKLGSC5AJ1JQDFWJ8V3PKHBIDNX_INDEX_4", Quest.QUEST, new OrderField[] { Quest.QUEST.USER_ID }, false);
        public static Index PRIMARY_KEY_49 = Internal.createIndex("PRIMARY_KEY_49", Quest.QUEST, new OrderField[] { Quest.QUEST.ID }, true);
        public static Index FKJ20N6BQIYJ8MVBJWR5EXDH37T_INDEX_1 = Internal.createIndex("FKJ20N6BQIYJ8MVBJWR5EXDH37T_INDEX_1", QuestReport.QUEST_REPORT, new OrderField[] { QuestReport.QUEST_REPORT.QUEST_ID }, false);
        public static Index FKODP2V6API3IL5GL748PXYPKWJ_INDEX_1 = Internal.createIndex("FKODP2V6API3IL5GL748PXYPKWJ_INDEX_1", QuestReport.QUEST_REPORT, new OrderField[] { QuestReport.QUEST_REPORT.USER_ID }, false);
        public static Index PRIMARY_KEY_10 = Internal.createIndex("PRIMARY_KEY_10", QuestReport.QUEST_REPORT, new OrderField[] { QuestReport.QUEST_REPORT.ID }, true);
        public static Index FK1HJWWRR4XDDJJ9C7IICVVM78J_INDEX_1 = Internal.createIndex("FK1HJWWRR4XDDJJ9C7IICVVM78J_INDEX_1", QuestReview.QUEST_REVIEW, new OrderField[] { QuestReview.QUEST_REVIEW.QUEST_ID }, false);
        public static Index FKQG1FBVCAVQ2LBPP8G8W8VTIAM_INDEX_1 = Internal.createIndex("FKQG1FBVCAVQ2LBPP8G8W8VTIAM_INDEX_1", QuestReview.QUEST_REVIEW, new OrderField[] { QuestReview.QUEST_REVIEW.USER_ID }, false);
        public static Index PRIMARY_KEY_105 = Internal.createIndex("PRIMARY_KEY_105", QuestReview.QUEST_REVIEW, new OrderField[] { QuestReview.QUEST_REVIEW.ID }, true);
        public static Index PRIMARY_KEY_26 = Internal.createIndex("PRIMARY_KEY_26", Role.ROLE, new OrderField[] { Role.ROLE.ID }, true);
        public static Index PRIMARY_KEY_26B = Internal.createIndex("PRIMARY_KEY_26B", Sale.SALE, new OrderField[] { Sale.SALE.ID }, true);
        public static Index FKMUJKS4H5F77VK9X2HH1L4YPVG_INDEX_4 = Internal.createIndex("FKMUJKS4H5F77VK9X2HH1L4YPVG_INDEX_4", Stage.STAGE, new OrderField[] { Stage.STAGE.QUEST_ID }, false);
        public static Index PRIMARY_KEY_4B = Internal.createIndex("PRIMARY_KEY_4B", Stage.STAGE, new OrderField[] { Stage.STAGE.ID }, true);
        public static Index FKE32EK7IXANAKFQSDAOKM4Q9Y2_INDEX_4 = Internal.createIndex("FKE32EK7IXANAKFQSDAOKM4Q9Y2_INDEX_4", Token.TOKEN, new OrderField[] { Token.TOKEN.USER_ID }, false);
        public static Index PRIMARY_KEY_4C = Internal.createIndex("PRIMARY_KEY_4C", Token.TOKEN, new OrderField[] { Token.TOKEN.ID }, true);
        public static Index FKSG7JP0AJ6QIPR50856WF6VBW1_INDEX_F = Internal.createIndex("FKSG7JP0AJ6QIPR50856WF6VBW1_INDEX_F", Transaction.TRANSACTION, new OrderField[] { Transaction.TRANSACTION.USER_ID }, false);
        public static Index PRIMARY_KEY_F = Internal.createIndex("PRIMARY_KEY_F", Transaction.TRANSACTION, new OrderField[] { Transaction.TRANSACTION.ID }, true);
        public static Index PRIMARY_KEY_27 = Internal.createIndex("PRIMARY_KEY_27", User.USER, new OrderField[] { User.USER.ID }, true);
        public static Index UK_D2IA11OQHSYNODBSI46M80VFC_INDEX_2 = Internal.createIndex("UK_D2IA11OQHSYNODBSI46M80VFC_INDEX_2", User.USER, new OrderField[] { User.USER.NICK_NAME }, true);
        public static Index UK_OB8KQYQQGMEFL0ACO34AKDTPE_INDEX_2 = Internal.createIndex("UK_OB8KQYQQGMEFL0ACO34AKDTPE_INDEX_2", User.USER, new OrderField[] { User.USER.EMAIL }, true);
        public static Index FK2JW9FPOTMMBDA07K27QC9T2UL_INDEX_C = Internal.createIndex("FK2JW9FPOTMMBDA07K27QC9T2UL_INDEX_C", UserBadge.USER_BADGE, new OrderField[] { UserBadge.USER_BADGE.USER_ID }, false);
        public static Index FKJQX9N26PK9MQF1QO8F7XVVOQ9_INDEX_C = Internal.createIndex("FKJQX9N26PK9MQF1QO8F7XVVOQ9_INDEX_C", UserBadge.USER_BADGE, new OrderField[] { UserBadge.USER_BADGE.BADGE_ID }, false);
        public static Index PRIMARY_KEY_C5 = Internal.createIndex("PRIMARY_KEY_C5", UserBadge.USER_BADGE, new OrderField[] { UserBadge.USER_BADGE.ID }, true);
        public static Index FK8USX5LQY3O113K7K4436XBERW_INDEX_D = Internal.createIndex("FK8USX5LQY3O113K7K4436XBERW_INDEX_D", UserOption.USER_OPTION, new OrderField[] { UserOption.USER_OPTION.USER_ID }, false);
        public static Index FKR6EERMF5AQ2NUA7HSSPMFFG02_INDEX_D = Internal.createIndex("FKR6EERMF5AQ2NUA7HSSPMFFG02_INDEX_D", UserOption.USER_OPTION, new OrderField[] { UserOption.USER_OPTION.LANGUAGE_ID }, false);
        public static Index PRIMARY_KEY_D = Internal.createIndex("PRIMARY_KEY_D", UserOption.USER_OPTION, new OrderField[] { UserOption.USER_OPTION.ID }, true);
        public static Index FK8JDYAKV4ATARQD05U7AXUBMYK_INDEX_C = Internal.createIndex("FK8JDYAKV4ATARQD05U7AXUBMYK_INDEX_C", UserQuest.USER_QUEST, new OrderField[] { UserQuest.USER_QUEST.USER_ID }, false);
        public static Index FKKMK9IF2IG0F3GQ6TTISKHIO7C_INDEX_C = Internal.createIndex("FKKMK9IF2IG0F3GQ6TTISKHIO7C_INDEX_C", UserQuest.USER_QUEST, new OrderField[] { UserQuest.USER_QUEST.STAGE_ID }, false);
        public static Index PRIMARY_KEY_C6 = Internal.createIndex("PRIMARY_KEY_C6", UserQuest.USER_QUEST, new OrderField[] { UserQuest.USER_QUEST.ID }, true);
        public static Index FK2CM7CI55E41B6EAKUNXYDH3LG_INDEX_1 = Internal.createIndex("FK2CM7CI55E41B6EAKUNXYDH3LG_INDEX_1", UserReport.USER_REPORT, new OrderField[] { UserReport.USER_REPORT.COMPLAINANT }, false);
        public static Index FKO1LNULINQCBVABO3W4NI3K4D1_INDEX_1 = Internal.createIndex("FKO1LNULINQCBVABO3W4NI3K4D1_INDEX_1", UserReport.USER_REPORT, new OrderField[] { UserReport.USER_REPORT.REPORTED }, false);
        public static Index PRIMARY_KEY_11 = Internal.createIndex("PRIMARY_KEY_11", UserReport.USER_REPORT, new OrderField[] { UserReport.USER_REPORT.ID }, true);
        public static Index FK859N2JVI8IVHUI0RL0ESWS6O_INDEX_B = Internal.createIndex("FK859N2JVI8IVHUI0RL0ESWS6O_INDEX_B", UserRole.USER_ROLE, new OrderField[] { UserRole.USER_ROLE.USER_ID }, false);
        public static Index FKA68196081FVOVJHKEK5M97N3Y_INDEX_B = Internal.createIndex("FKA68196081FVOVJHKEK5M97N3Y_INDEX_B", UserRole.USER_ROLE, new OrderField[] { UserRole.USER_ROLE.ROLE_ID }, false);
        public static Index PRIMARY_KEY_B = Internal.createIndex("PRIMARY_KEY_B", UserRole.USER_ROLE, new OrderField[] { UserRole.USER_ROLE.ID }, true);
    }
}
