/*
 * This file is generated by jOOQ.
 */
package com.geoly.app.jooq;


import com.geoly.app.jooq.tables.Badge;
import com.geoly.app.jooq.tables.Category;
import com.geoly.app.jooq.tables.Image;
import com.geoly.app.jooq.tables.Language;
import com.geoly.app.jooq.tables.Party;
import com.geoly.app.jooq.tables.PartyInvite;
import com.geoly.app.jooq.tables.PartyQuest;
import com.geoly.app.jooq.tables.PartyUser;
import com.geoly.app.jooq.tables.Point;
import com.geoly.app.jooq.tables.Premium;
import com.geoly.app.jooq.tables.Quest;
import com.geoly.app.jooq.tables.QuestReport;
import com.geoly.app.jooq.tables.QuestReview;
import com.geoly.app.jooq.tables.Role;
import com.geoly.app.jooq.tables.Sale;
import com.geoly.app.jooq.tables.Stage;
import com.geoly.app.jooq.tables.Token;
import com.geoly.app.jooq.tables.User;
import com.geoly.app.jooq.tables.UserBadge;
import com.geoly.app.jooq.tables.UserOption;
import com.geoly.app.jooq.tables.UserQuest;
import com.geoly.app.jooq.tables.UserReport;
import com.geoly.app.jooq.tables.UserRole;
import com.geoly.app.jooq.tables.records.BadgeRecord;
import com.geoly.app.jooq.tables.records.CategoryRecord;
import com.geoly.app.jooq.tables.records.ImageRecord;
import com.geoly.app.jooq.tables.records.LanguageRecord;
import com.geoly.app.jooq.tables.records.PartyInviteRecord;
import com.geoly.app.jooq.tables.records.PartyQuestRecord;
import com.geoly.app.jooq.tables.records.PartyRecord;
import com.geoly.app.jooq.tables.records.PartyUserRecord;
import com.geoly.app.jooq.tables.records.PointRecord;
import com.geoly.app.jooq.tables.records.PremiumRecord;
import com.geoly.app.jooq.tables.records.QuestRecord;
import com.geoly.app.jooq.tables.records.QuestReportRecord;
import com.geoly.app.jooq.tables.records.QuestReviewRecord;
import com.geoly.app.jooq.tables.records.RoleRecord;
import com.geoly.app.jooq.tables.records.SaleRecord;
import com.geoly.app.jooq.tables.records.StageRecord;
import com.geoly.app.jooq.tables.records.TokenRecord;
import com.geoly.app.jooq.tables.records.UserBadgeRecord;
import com.geoly.app.jooq.tables.records.UserOptionRecord;
import com.geoly.app.jooq.tables.records.UserQuestRecord;
import com.geoly.app.jooq.tables.records.UserRecord;
import com.geoly.app.jooq.tables.records.UserReportRecord;
import com.geoly.app.jooq.tables.records.UserRoleRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>geoly</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<BadgeRecord> CONSTRAINT_3 = UniqueKeys0.CONSTRAINT_3;
    public static final UniqueKey<CategoryRecord> CONSTRAINT_31 = UniqueKeys0.CONSTRAINT_31;
    public static final UniqueKey<ImageRecord> CONSTRAINT_4 = UniqueKeys0.CONSTRAINT_4;
    public static final UniqueKey<LanguageRecord> CONSTRAINT_C = UniqueKeys0.CONSTRAINT_C;
    public static final UniqueKey<PartyRecord> CONSTRAINT_48 = UniqueKeys0.CONSTRAINT_48;
    public static final UniqueKey<PartyInviteRecord> CONSTRAINT_5 = UniqueKeys0.CONSTRAINT_5;
    public static final UniqueKey<PartyQuestRecord> CONSTRAINT_2 = UniqueKeys0.CONSTRAINT_2;
    public static final UniqueKey<PartyUserRecord> CONSTRAINT_3B = UniqueKeys0.CONSTRAINT_3B;
    public static final UniqueKey<PointRecord> CONSTRAINT_48C = UniqueKeys0.CONSTRAINT_48C;
    public static final UniqueKey<PremiumRecord> CONSTRAINT_1 = UniqueKeys0.CONSTRAINT_1;
    public static final UniqueKey<QuestRecord> CONSTRAINT_49 = UniqueKeys0.CONSTRAINT_49;
    public static final UniqueKey<QuestReportRecord> CONSTRAINT_10 = UniqueKeys0.CONSTRAINT_10;
    public static final UniqueKey<QuestReviewRecord> CONSTRAINT_105 = UniqueKeys0.CONSTRAINT_105;
    public static final UniqueKey<QuestReviewRecord> UKBO8AKQYL97OHGFN6T4O83Q6DR = UniqueKeys0.UKBO8AKQYL97OHGFN6T4O83Q6DR;
    public static final UniqueKey<RoleRecord> CONSTRAINT_26 = UniqueKeys0.CONSTRAINT_26;
    public static final UniqueKey<SaleRecord> CONSTRAINT_26B = UniqueKeys0.CONSTRAINT_26B;
    public static final UniqueKey<StageRecord> CONSTRAINT_4B = UniqueKeys0.CONSTRAINT_4B;
    public static final UniqueKey<TokenRecord> CONSTRAINT_4C = UniqueKeys0.CONSTRAINT_4C;
    public static final UniqueKey<UserRecord> CONSTRAINT_27 = UniqueKeys0.CONSTRAINT_27;
    public static final UniqueKey<UserRecord> UK_OB8KQYQQGMEFL0ACO34AKDTPE = UniqueKeys0.UK_OB8KQYQQGMEFL0ACO34AKDTPE;
    public static final UniqueKey<UserRecord> UK_D2IA11OQHSYNODBSI46M80VFC = UniqueKeys0.UK_D2IA11OQHSYNODBSI46M80VFC;
    public static final UniqueKey<UserBadgeRecord> CONSTRAINT_C5 = UniqueKeys0.CONSTRAINT_C5;
    public static final UniqueKey<UserOptionRecord> CONSTRAINT_D = UniqueKeys0.CONSTRAINT_D;
    public static final UniqueKey<UserQuestRecord> CONSTRAINT_C6 = UniqueKeys0.CONSTRAINT_C6;
    public static final UniqueKey<UserReportRecord> CONSTRAINT_11 = UniqueKeys0.CONSTRAINT_11;
    public static final UniqueKey<UserReportRecord> UKPT3UYBUWE0QPIJ09B9LHQV52S = UniqueKeys0.UKPT3UYBUWE0QPIJ09B9LHQV52S;
    public static final UniqueKey<UserRoleRecord> CONSTRAINT_B = UniqueKeys0.CONSTRAINT_B;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ImageRecord, QuestRecord> FK3N5NEGXV9EYM0STD2EUTTVG6W = ForeignKeys0.FK3N5NEGXV9EYM0STD2EUTTVG6W;
    public static final ForeignKey<PartyRecord, UserRecord> FKTCAG4FSDQKMO7OWJKK1P25H41 = ForeignKeys0.FKTCAG4FSDQKMO7OWJKK1P25H41;
    public static final ForeignKey<PartyInviteRecord, PartyRecord> FKG0D7MD7NQV6Y8UNXO7TFR722F = ForeignKeys0.FKG0D7MD7NQV6Y8UNXO7TFR722F;
    public static final ForeignKey<PartyInviteRecord, UserRecord> FK5N5BG86WU1LEDOPG6IN964H6J = ForeignKeys0.FK5N5BG86WU1LEDOPG6IN964H6J;
    public static final ForeignKey<PartyQuestRecord, PartyRecord> FK2GIGO39GG9CLIMKUAALBB2OD0 = ForeignKeys0.FK2GIGO39GG9CLIMKUAALBB2OD0;
    public static final ForeignKey<PartyQuestRecord, QuestRecord> FK8FL0NU8HGJ8JESC5HPWBIO1UB = ForeignKeys0.FK8FL0NU8HGJ8JESC5HPWBIO1UB;
    public static final ForeignKey<PartyUserRecord, PartyRecord> FKOATBT6TV26KK2R5VGUA7OJSM = ForeignKeys0.FKOATBT6TV26KK2R5VGUA7OJSM;
    public static final ForeignKey<PartyUserRecord, UserRecord> FKGBM3CRUYQ6N25LRIIYC2XAD43 = ForeignKeys0.FKGBM3CRUYQ6N25LRIIYC2XAD43;
    public static final ForeignKey<PointRecord, UserRecord> FKH4QXMN9MIG6KITH0ISH2R67KA = ForeignKeys0.FKH4QXMN9MIG6KITH0ISH2R67KA;
    public static final ForeignKey<PremiumRecord, UserRecord> FK55RHAW7HB4IB9USGJD0RVYUBB = ForeignKeys0.FK55RHAW7HB4IB9USGJD0RVYUBB;
    public static final ForeignKey<QuestRecord, CategoryRecord> FK4FOEBLYDMUA10QB2OEUANE6FB = ForeignKeys0.FK4FOEBLYDMUA10QB2OEUANE6FB;
    public static final ForeignKey<QuestRecord, UserRecord> FKLGSC5AJ1JQDFWJ8V3PKHBIDNX = ForeignKeys0.FKLGSC5AJ1JQDFWJ8V3PKHBIDNX;
    public static final ForeignKey<QuestReportRecord, QuestRecord> FKJ20N6BQIYJ8MVBJWR5EXDH37T = ForeignKeys0.FKJ20N6BQIYJ8MVBJWR5EXDH37T;
    public static final ForeignKey<QuestReportRecord, UserRecord> FKODP2V6API3IL5GL748PXYPKWJ = ForeignKeys0.FKODP2V6API3IL5GL748PXYPKWJ;
    public static final ForeignKey<QuestReviewRecord, QuestRecord> FK1HJWWRR4XDDJJ9C7IICVVM78J = ForeignKeys0.FK1HJWWRR4XDDJJ9C7IICVVM78J;
    public static final ForeignKey<QuestReviewRecord, UserRecord> FKQG1FBVCAVQ2LBPP8G8W8VTIAM = ForeignKeys0.FKQG1FBVCAVQ2LBPP8G8W8VTIAM;
    public static final ForeignKey<StageRecord, QuestRecord> FKMUJKS4H5F77VK9X2HH1L4YPVG = ForeignKeys0.FKMUJKS4H5F77VK9X2HH1L4YPVG;
    public static final ForeignKey<TokenRecord, UserRecord> FKE32EK7IXANAKFQSDAOKM4Q9Y2 = ForeignKeys0.FKE32EK7IXANAKFQSDAOKM4Q9Y2;
    public static final ForeignKey<UserBadgeRecord, BadgeRecord> FKJQX9N26PK9MQF1QO8F7XVVOQ9 = ForeignKeys0.FKJQX9N26PK9MQF1QO8F7XVVOQ9;
    public static final ForeignKey<UserBadgeRecord, UserRecord> FK2JW9FPOTMMBDA07K27QC9T2UL = ForeignKeys0.FK2JW9FPOTMMBDA07K27QC9T2UL;
    public static final ForeignKey<UserOptionRecord, LanguageRecord> FKR6EERMF5AQ2NUA7HSSPMFFG02 = ForeignKeys0.FKR6EERMF5AQ2NUA7HSSPMFFG02;
    public static final ForeignKey<UserOptionRecord, UserRecord> FK8USX5LQY3O113K7K4436XBERW = ForeignKeys0.FK8USX5LQY3O113K7K4436XBERW;
    public static final ForeignKey<UserQuestRecord, StageRecord> FKKMK9IF2IG0F3GQ6TTISKHIO7C = ForeignKeys0.FKKMK9IF2IG0F3GQ6TTISKHIO7C;
    public static final ForeignKey<UserQuestRecord, UserRecord> FK8JDYAKV4ATARQD05U7AXUBMYK = ForeignKeys0.FK8JDYAKV4ATARQD05U7AXUBMYK;
    public static final ForeignKey<UserReportRecord, UserRecord> FK2CM7CI55E41B6EAKUNXYDH3LG = ForeignKeys0.FK2CM7CI55E41B6EAKUNXYDH3LG;
    public static final ForeignKey<UserReportRecord, UserRecord> FKO1LNULINQCBVABO3W4NI3K4D1 = ForeignKeys0.FKO1LNULINQCBVABO3W4NI3K4D1;
    public static final ForeignKey<UserRoleRecord, UserRecord> FK859N2JVI8IVHUI0RL0ESWS6O = ForeignKeys0.FK859N2JVI8IVHUI0RL0ESWS6O;
    public static final ForeignKey<UserRoleRecord, RoleRecord> FKA68196081FVOVJHKEK5M97N3Y = ForeignKeys0.FKA68196081FVOVJHKEK5M97N3Y;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<BadgeRecord> CONSTRAINT_3 = Internal.createUniqueKey(Badge.BADGE, "CONSTRAINT_3", Badge.BADGE.ID);
        public static final UniqueKey<CategoryRecord> CONSTRAINT_31 = Internal.createUniqueKey(Category.CATEGORY, "CONSTRAINT_31", Category.CATEGORY.ID);
        public static final UniqueKey<ImageRecord> CONSTRAINT_4 = Internal.createUniqueKey(Image.IMAGE, "CONSTRAINT_4", Image.IMAGE.ID);
        public static final UniqueKey<LanguageRecord> CONSTRAINT_C = Internal.createUniqueKey(Language.LANGUAGE, "CONSTRAINT_C", Language.LANGUAGE.ID);
        public static final UniqueKey<PartyRecord> CONSTRAINT_48 = Internal.createUniqueKey(Party.PARTY, "CONSTRAINT_48", Party.PARTY.ID);
        public static final UniqueKey<PartyInviteRecord> CONSTRAINT_5 = Internal.createUniqueKey(PartyInvite.PARTY_INVITE, "CONSTRAINT_5", PartyInvite.PARTY_INVITE.ID);
        public static final UniqueKey<PartyQuestRecord> CONSTRAINT_2 = Internal.createUniqueKey(PartyQuest.PARTY_QUEST, "CONSTRAINT_2", PartyQuest.PARTY_QUEST.ID);
        public static final UniqueKey<PartyUserRecord> CONSTRAINT_3B = Internal.createUniqueKey(PartyUser.PARTY_USER, "CONSTRAINT_3B", PartyUser.PARTY_USER.ID);
        public static final UniqueKey<PointRecord> CONSTRAINT_48C = Internal.createUniqueKey(Point.POINT, "CONSTRAINT_48C", Point.POINT.ID);
        public static final UniqueKey<PremiumRecord> CONSTRAINT_1 = Internal.createUniqueKey(Premium.PREMIUM, "CONSTRAINT_1", Premium.PREMIUM.ID);
        public static final UniqueKey<QuestRecord> CONSTRAINT_49 = Internal.createUniqueKey(Quest.QUEST, "CONSTRAINT_49", Quest.QUEST.ID);
        public static final UniqueKey<QuestReportRecord> CONSTRAINT_10 = Internal.createUniqueKey(QuestReport.QUEST_REPORT, "CONSTRAINT_10", QuestReport.QUEST_REPORT.ID);
        public static final UniqueKey<QuestReviewRecord> CONSTRAINT_105 = Internal.createUniqueKey(QuestReview.QUEST_REVIEW, "CONSTRAINT_105", QuestReview.QUEST_REVIEW.ID);
        public static final UniqueKey<QuestReviewRecord> UKBO8AKQYL97OHGFN6T4O83Q6DR = Internal.createUniqueKey(QuestReview.QUEST_REVIEW, "UKBO8AKQYL97OHGFN6T4O83Q6DR", QuestReview.QUEST_REVIEW.USER_ID, QuestReview.QUEST_REVIEW.QUEST_ID);
        public static final UniqueKey<RoleRecord> CONSTRAINT_26 = Internal.createUniqueKey(Role.ROLE, "CONSTRAINT_26", Role.ROLE.ID);
        public static final UniqueKey<SaleRecord> CONSTRAINT_26B = Internal.createUniqueKey(Sale.SALE, "CONSTRAINT_26B", Sale.SALE.ID);
        public static final UniqueKey<StageRecord> CONSTRAINT_4B = Internal.createUniqueKey(Stage.STAGE, "CONSTRAINT_4B", Stage.STAGE.ID);
        public static final UniqueKey<TokenRecord> CONSTRAINT_4C = Internal.createUniqueKey(Token.TOKEN, "CONSTRAINT_4C", Token.TOKEN.ID);
        public static final UniqueKey<UserRecord> CONSTRAINT_27 = Internal.createUniqueKey(User.USER, "CONSTRAINT_27", User.USER.ID);
        public static final UniqueKey<UserRecord> UK_OB8KQYQQGMEFL0ACO34AKDTPE = Internal.createUniqueKey(User.USER, "UK_OB8KQYQQGMEFL0ACO34AKDTPE", User.USER.EMAIL);
        public static final UniqueKey<UserRecord> UK_D2IA11OQHSYNODBSI46M80VFC = Internal.createUniqueKey(User.USER, "UK_D2IA11OQHSYNODBSI46M80VFC", User.USER.NICK_NAME);
        public static final UniqueKey<UserBadgeRecord> CONSTRAINT_C5 = Internal.createUniqueKey(UserBadge.USER_BADGE, "CONSTRAINT_C5", UserBadge.USER_BADGE.ID);
        public static final UniqueKey<UserOptionRecord> CONSTRAINT_D = Internal.createUniqueKey(UserOption.USER_OPTION, "CONSTRAINT_D", UserOption.USER_OPTION.ID);
        public static final UniqueKey<UserQuestRecord> CONSTRAINT_C6 = Internal.createUniqueKey(UserQuest.USER_QUEST, "CONSTRAINT_C6", UserQuest.USER_QUEST.ID);
        public static final UniqueKey<UserReportRecord> CONSTRAINT_11 = Internal.createUniqueKey(UserReport.USER_REPORT, "CONSTRAINT_11", UserReport.USER_REPORT.ID);
        public static final UniqueKey<UserReportRecord> UKPT3UYBUWE0QPIJ09B9LHQV52S = Internal.createUniqueKey(UserReport.USER_REPORT, "UKPT3UYBUWE0QPIJ09B9LHQV52S", UserReport.USER_REPORT.REPORTED, UserReport.USER_REPORT.COMPLAINANT);
        public static final UniqueKey<UserRoleRecord> CONSTRAINT_B = Internal.createUniqueKey(UserRole.USER_ROLE, "CONSTRAINT_B", UserRole.USER_ROLE.USER_ID, UserRole.USER_ROLE.ROLE_ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<ImageRecord, QuestRecord> FK3N5NEGXV9EYM0STD2EUTTVG6W = Internal.createForeignKey(com.geoly.app.jooq.Keys.CONSTRAINT_49, Image.IMAGE, "FK3N5NEGXV9EYM0STD2EUTTVG6W", Image.IMAGE.QUEST_ID);
        public static final ForeignKey<PartyRecord, UserRecord> FKTCAG4FSDQKMO7OWJKK1P25H41 = Internal.createForeignKey(com.geoly.app.jooq.Keys.CONSTRAINT_27, Party.PARTY, "FKTCAG4FSDQKMO7OWJKK1P25H41", Party.PARTY.USER_ID);
        public static final ForeignKey<PartyInviteRecord, PartyRecord> FKG0D7MD7NQV6Y8UNXO7TFR722F = Internal.createForeignKey(com.geoly.app.jooq.Keys.CONSTRAINT_48, PartyInvite.PARTY_INVITE, "FKG0D7MD7NQV6Y8UNXO7TFR722F", PartyInvite.PARTY_INVITE.PARTY_ID);
        public static final ForeignKey<PartyInviteRecord, UserRecord> FK5N5BG86WU1LEDOPG6IN964H6J = Internal.createForeignKey(com.geoly.app.jooq.Keys.CONSTRAINT_27, PartyInvite.PARTY_INVITE, "FK5N5BG86WU1LEDOPG6IN964H6J", PartyInvite.PARTY_INVITE.USER_ID);
        public static final ForeignKey<PartyQuestRecord, PartyRecord> FK2GIGO39GG9CLIMKUAALBB2OD0 = Internal.createForeignKey(com.geoly.app.jooq.Keys.CONSTRAINT_48, PartyQuest.PARTY_QUEST, "FK2GIGO39GG9CLIMKUAALBB2OD0", PartyQuest.PARTY_QUEST.PARTY_ID);
        public static final ForeignKey<PartyQuestRecord, QuestRecord> FK8FL0NU8HGJ8JESC5HPWBIO1UB = Internal.createForeignKey(com.geoly.app.jooq.Keys.CONSTRAINT_49, PartyQuest.PARTY_QUEST, "FK8FL0NU8HGJ8JESC5HPWBIO1UB", PartyQuest.PARTY_QUEST.QUEST_ID);
        public static final ForeignKey<PartyUserRecord, PartyRecord> FKOATBT6TV26KK2R5VGUA7OJSM = Internal.createForeignKey(com.geoly.app.jooq.Keys.CONSTRAINT_48, PartyUser.PARTY_USER, "FKOATBT6TV26KK2R5VGUA7OJSM", PartyUser.PARTY_USER.PARTY_ID);
        public static final ForeignKey<PartyUserRecord, UserRecord> FKGBM3CRUYQ6N25LRIIYC2XAD43 = Internal.createForeignKey(com.geoly.app.jooq.Keys.CONSTRAINT_27, PartyUser.PARTY_USER, "FKGBM3CRUYQ6N25LRIIYC2XAD43", PartyUser.PARTY_USER.USER_ID);
        public static final ForeignKey<PointRecord, UserRecord> FKH4QXMN9MIG6KITH0ISH2R67KA = Internal.createForeignKey(com.geoly.app.jooq.Keys.CONSTRAINT_27, Point.POINT, "FKH4QXMN9MIG6KITH0ISH2R67KA", Point.POINT.USER_ID);
        public static final ForeignKey<PremiumRecord, UserRecord> FK55RHAW7HB4IB9USGJD0RVYUBB = Internal.createForeignKey(com.geoly.app.jooq.Keys.CONSTRAINT_27, Premium.PREMIUM, "FK55RHAW7HB4IB9USGJD0RVYUBB", Premium.PREMIUM.USER_ID);
        public static final ForeignKey<QuestRecord, CategoryRecord> FK4FOEBLYDMUA10QB2OEUANE6FB = Internal.createForeignKey(com.geoly.app.jooq.Keys.CONSTRAINT_31, Quest.QUEST, "FK4FOEBLYDMUA10QB2OEUANE6FB", Quest.QUEST.CATEGORY_ID);
        public static final ForeignKey<QuestRecord, UserRecord> FKLGSC5AJ1JQDFWJ8V3PKHBIDNX = Internal.createForeignKey(com.geoly.app.jooq.Keys.CONSTRAINT_27, Quest.QUEST, "FKLGSC5AJ1JQDFWJ8V3PKHBIDNX", Quest.QUEST.USER_ID);
        public static final ForeignKey<QuestReportRecord, QuestRecord> FKJ20N6BQIYJ8MVBJWR5EXDH37T = Internal.createForeignKey(com.geoly.app.jooq.Keys.CONSTRAINT_49, QuestReport.QUEST_REPORT, "FKJ20N6BQIYJ8MVBJWR5EXDH37T", QuestReport.QUEST_REPORT.QUEST_ID);
        public static final ForeignKey<QuestReportRecord, UserRecord> FKODP2V6API3IL5GL748PXYPKWJ = Internal.createForeignKey(com.geoly.app.jooq.Keys.CONSTRAINT_27, QuestReport.QUEST_REPORT, "FKODP2V6API3IL5GL748PXYPKWJ", QuestReport.QUEST_REPORT.USER_ID);
        public static final ForeignKey<QuestReviewRecord, QuestRecord> FK1HJWWRR4XDDJJ9C7IICVVM78J = Internal.createForeignKey(com.geoly.app.jooq.Keys.CONSTRAINT_49, QuestReview.QUEST_REVIEW, "FK1HJWWRR4XDDJJ9C7IICVVM78J", QuestReview.QUEST_REVIEW.QUEST_ID);
        public static final ForeignKey<QuestReviewRecord, UserRecord> FKQG1FBVCAVQ2LBPP8G8W8VTIAM = Internal.createForeignKey(com.geoly.app.jooq.Keys.CONSTRAINT_27, QuestReview.QUEST_REVIEW, "FKQG1FBVCAVQ2LBPP8G8W8VTIAM", QuestReview.QUEST_REVIEW.USER_ID);
        public static final ForeignKey<StageRecord, QuestRecord> FKMUJKS4H5F77VK9X2HH1L4YPVG = Internal.createForeignKey(com.geoly.app.jooq.Keys.CONSTRAINT_49, Stage.STAGE, "FKMUJKS4H5F77VK9X2HH1L4YPVG", Stage.STAGE.QUEST_ID);
        public static final ForeignKey<TokenRecord, UserRecord> FKE32EK7IXANAKFQSDAOKM4Q9Y2 = Internal.createForeignKey(com.geoly.app.jooq.Keys.CONSTRAINT_27, Token.TOKEN, "FKE32EK7IXANAKFQSDAOKM4Q9Y2", Token.TOKEN.USER_ID);
        public static final ForeignKey<UserBadgeRecord, BadgeRecord> FKJQX9N26PK9MQF1QO8F7XVVOQ9 = Internal.createForeignKey(com.geoly.app.jooq.Keys.CONSTRAINT_3, UserBadge.USER_BADGE, "FKJQX9N26PK9MQF1QO8F7XVVOQ9", UserBadge.USER_BADGE.BADGE_ID);
        public static final ForeignKey<UserBadgeRecord, UserRecord> FK2JW9FPOTMMBDA07K27QC9T2UL = Internal.createForeignKey(com.geoly.app.jooq.Keys.CONSTRAINT_27, UserBadge.USER_BADGE, "FK2JW9FPOTMMBDA07K27QC9T2UL", UserBadge.USER_BADGE.USER_ID);
        public static final ForeignKey<UserOptionRecord, LanguageRecord> FKR6EERMF5AQ2NUA7HSSPMFFG02 = Internal.createForeignKey(com.geoly.app.jooq.Keys.CONSTRAINT_C, UserOption.USER_OPTION, "FKR6EERMF5AQ2NUA7HSSPMFFG02", UserOption.USER_OPTION.LANGUAGE_ID);
        public static final ForeignKey<UserOptionRecord, UserRecord> FK8USX5LQY3O113K7K4436XBERW = Internal.createForeignKey(com.geoly.app.jooq.Keys.CONSTRAINT_27, UserOption.USER_OPTION, "FK8USX5LQY3O113K7K4436XBERW", UserOption.USER_OPTION.USER_ID);
        public static final ForeignKey<UserQuestRecord, StageRecord> FKKMK9IF2IG0F3GQ6TTISKHIO7C = Internal.createForeignKey(com.geoly.app.jooq.Keys.CONSTRAINT_4B, UserQuest.USER_QUEST, "FKKMK9IF2IG0F3GQ6TTISKHIO7C", UserQuest.USER_QUEST.STAGE_ID);
        public static final ForeignKey<UserQuestRecord, UserRecord> FK8JDYAKV4ATARQD05U7AXUBMYK = Internal.createForeignKey(com.geoly.app.jooq.Keys.CONSTRAINT_27, UserQuest.USER_QUEST, "FK8JDYAKV4ATARQD05U7AXUBMYK", UserQuest.USER_QUEST.USER_ID);
        public static final ForeignKey<UserReportRecord, UserRecord> FK2CM7CI55E41B6EAKUNXYDH3LG = Internal.createForeignKey(com.geoly.app.jooq.Keys.CONSTRAINT_27, UserReport.USER_REPORT, "FK2CM7CI55E41B6EAKUNXYDH3LG", UserReport.USER_REPORT.COMPLAINANT);
        public static final ForeignKey<UserReportRecord, UserRecord> FKO1LNULINQCBVABO3W4NI3K4D1 = Internal.createForeignKey(com.geoly.app.jooq.Keys.CONSTRAINT_27, UserReport.USER_REPORT, "FKO1LNULINQCBVABO3W4NI3K4D1", UserReport.USER_REPORT.REPORTED);
        public static final ForeignKey<UserRoleRecord, UserRecord> FK859N2JVI8IVHUI0RL0ESWS6O = Internal.createForeignKey(com.geoly.app.jooq.Keys.CONSTRAINT_27, UserRole.USER_ROLE, "FK859N2JVI8IVHUI0RL0ESWS6O", UserRole.USER_ROLE.USER_ID);
        public static final ForeignKey<UserRoleRecord, RoleRecord> FKA68196081FVOVJHKEK5M97N3Y = Internal.createForeignKey(com.geoly.app.jooq.Keys.CONSTRAINT_26, UserRole.USER_ROLE, "FKA68196081FVOVJHKEK5M97N3Y", UserRole.USER_ROLE.ROLE_ID);
    }
}
