/*
 * This file is generated by jOOQ.
 */
package com.geoly.app.jooq;


import com.geoly.app.jooq.tables.Badge;
import com.geoly.app.jooq.tables.Category;
import com.geoly.app.jooq.tables.Image;
import com.geoly.app.jooq.tables.Language;
import com.geoly.app.jooq.tables.Log;
import com.geoly.app.jooq.tables.Notification;
import com.geoly.app.jooq.tables.Party;
import com.geoly.app.jooq.tables.PartyInvite;
import com.geoly.app.jooq.tables.PartyQuest;
import com.geoly.app.jooq.tables.PartyUser;
import com.geoly.app.jooq.tables.Point;
import com.geoly.app.jooq.tables.Premium;
import com.geoly.app.jooq.tables.Quest;
import com.geoly.app.jooq.tables.QuestReport;
import com.geoly.app.jooq.tables.QuestReview;
import com.geoly.app.jooq.tables.Role;
import com.geoly.app.jooq.tables.Stage;
import com.geoly.app.jooq.tables.Token;
import com.geoly.app.jooq.tables.User;
import com.geoly.app.jooq.tables.UserBadge;
import com.geoly.app.jooq.tables.UserOption;
import com.geoly.app.jooq.tables.UserPartyQuest;
import com.geoly.app.jooq.tables.UserQuest;
import com.geoly.app.jooq.tables.UserReport;
import com.geoly.app.jooq.tables.UserRole;
import com.geoly.app.jooq.tables.records.BadgeRecord;
import com.geoly.app.jooq.tables.records.CategoryRecord;
import com.geoly.app.jooq.tables.records.ImageRecord;
import com.geoly.app.jooq.tables.records.LanguageRecord;
import com.geoly.app.jooq.tables.records.LogRecord;
import com.geoly.app.jooq.tables.records.NotificationRecord;
import com.geoly.app.jooq.tables.records.PartyInviteRecord;
import com.geoly.app.jooq.tables.records.PartyQuestRecord;
import com.geoly.app.jooq.tables.records.PartyRecord;
import com.geoly.app.jooq.tables.records.PartyUserRecord;
import com.geoly.app.jooq.tables.records.PointRecord;
import com.geoly.app.jooq.tables.records.PremiumRecord;
import com.geoly.app.jooq.tables.records.QuestRecord;
import com.geoly.app.jooq.tables.records.QuestReportRecord;
import com.geoly.app.jooq.tables.records.QuestReviewRecord;
import com.geoly.app.jooq.tables.records.RoleRecord;
import com.geoly.app.jooq.tables.records.StageRecord;
import com.geoly.app.jooq.tables.records.TokenRecord;
import com.geoly.app.jooq.tables.records.UserBadgeRecord;
import com.geoly.app.jooq.tables.records.UserOptionRecord;
import com.geoly.app.jooq.tables.records.UserPartyQuestRecord;
import com.geoly.app.jooq.tables.records.UserQuestRecord;
import com.geoly.app.jooq.tables.records.UserRecord;
import com.geoly.app.jooq.tables.records.UserReportRecord;
import com.geoly.app.jooq.tables.records.UserRoleRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>geoly</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<BadgeRecord> CONSTRAINT_3 = UniqueKeys0.CONSTRAINT_3;
    public static final UniqueKey<CategoryRecord> CONSTRAINT_31 = UniqueKeys0.CONSTRAINT_31;
    public static final UniqueKey<ImageRecord> CONSTRAINT_4 = UniqueKeys0.CONSTRAINT_4;
    public static final UniqueKey<LanguageRecord> CONSTRAINT_C = UniqueKeys0.CONSTRAINT_C;
    public static final UniqueKey<LogRecord> CONSTRAINT_1 = UniqueKeys0.CONSTRAINT_1;
    public static final UniqueKey<NotificationRecord> CONSTRAINT_A = UniqueKeys0.CONSTRAINT_A;
    public static final UniqueKey<PartyRecord> CONSTRAINT_48 = UniqueKeys0.CONSTRAINT_48;
    public static final UniqueKey<PartyInviteRecord> CONSTRAINT_5 = UniqueKeys0.CONSTRAINT_5;
    public static final UniqueKey<PartyQuestRecord> CONSTRAINT_2 = UniqueKeys0.CONSTRAINT_2;
    public static final UniqueKey<PartyUserRecord> CONSTRAINT_3B = UniqueKeys0.CONSTRAINT_3B;
    public static final UniqueKey<PointRecord> CONSTRAINT_48C = UniqueKeys0.CONSTRAINT_48C;
    public static final UniqueKey<PremiumRecord> CONSTRAINT_17 = UniqueKeys0.CONSTRAINT_17;
    public static final UniqueKey<QuestRecord> CONSTRAINT_49 = UniqueKeys0.CONSTRAINT_49;
    public static final UniqueKey<QuestReportRecord> CONSTRAINT_10 = UniqueKeys0.CONSTRAINT_10;
    public static final UniqueKey<QuestReviewRecord> CONSTRAINT_105 = UniqueKeys0.CONSTRAINT_105;
    public static final UniqueKey<QuestReviewRecord> UKTIP5DD0129ALBKCV3KRX41IBO = UniqueKeys0.UKTIP5DD0129ALBKCV3KRX41IBO;
    public static final UniqueKey<RoleRecord> CONSTRAINT_26 = UniqueKeys0.CONSTRAINT_26;
    public static final UniqueKey<StageRecord> CONSTRAINT_4B = UniqueKeys0.CONSTRAINT_4B;
    public static final UniqueKey<TokenRecord> CONSTRAINT_4C = UniqueKeys0.CONSTRAINT_4C;
    public static final UniqueKey<UserRecord> CONSTRAINT_27 = UniqueKeys0.CONSTRAINT_27;
    public static final UniqueKey<UserRecord> UK_OSO07PUDW19E66BS4YP8HWPUX = UniqueKeys0.UK_OSO07PUDW19E66BS4YP8HWPUX;
    public static final UniqueKey<UserRecord> UK_41DMWQT0G1WFLBC7PNQHER1A = UniqueKeys0.UK_41DMWQT0G1WFLBC7PNQHER1A;
    public static final UniqueKey<UserBadgeRecord> CONSTRAINT_C5 = UniqueKeys0.CONSTRAINT_C5;
    public static final UniqueKey<UserOptionRecord> CONSTRAINT_D = UniqueKeys0.CONSTRAINT_D;
    public static final UniqueKey<UserPartyQuestRecord> CONSTRAINT_55 = UniqueKeys0.CONSTRAINT_55;
    public static final UniqueKey<UserQuestRecord> CONSTRAINT_C6 = UniqueKeys0.CONSTRAINT_C6;
    public static final UniqueKey<UserReportRecord> CONSTRAINT_11 = UniqueKeys0.CONSTRAINT_11;
    public static final UniqueKey<UserReportRecord> UKD8H5NIRV4QEVOSRD38T6ATCD6 = UniqueKeys0.UKD8H5NIRV4QEVOSRD38T6ATCD6;
    public static final UniqueKey<UserRoleRecord> CONSTRAINT_B = UniqueKeys0.CONSTRAINT_B;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ImageRecord, QuestRecord> FK4RXXT2CJB76UV4J43SL3QAY2H = ForeignKeys0.FK4RXXT2CJB76UV4J43SL3QAY2H;
    public static final ForeignKey<NotificationRecord, UserRecord> FK16C2APDKEL73R81ED2DPWV0A2 = ForeignKeys0.FK16C2APDKEL73R81ED2DPWV0A2;
    public static final ForeignKey<PartyRecord, UserRecord> FKQFWC76LQ1GWTEVTA6KHS862RK = ForeignKeys0.FKQFWC76LQ1GWTEVTA6KHS862RK;
    public static final ForeignKey<PartyInviteRecord, PartyRecord> FKECYTUNFMMOIEEEIW7NAQ57UYE = ForeignKeys0.FKECYTUNFMMOIEEEIW7NAQ57UYE;
    public static final ForeignKey<PartyInviteRecord, UserRecord> FK5H11DMN0OV3Y30CYVN01NOUR3 = ForeignKeys0.FK5H11DMN0OV3Y30CYVN01NOUR3;
    public static final ForeignKey<PartyQuestRecord, PartyRecord> FK4BFMT3TPKS38SN4GW97VYHEM3 = ForeignKeys0.FK4BFMT3TPKS38SN4GW97VYHEM3;
    public static final ForeignKey<PartyQuestRecord, QuestRecord> FKHFLFH9KMNL4BFFJFQH57IGR76 = ForeignKeys0.FKHFLFH9KMNL4BFFJFQH57IGR76;
    public static final ForeignKey<PartyUserRecord, PartyRecord> FKDR8M467PUQDLNX5JY42ULLE41 = ForeignKeys0.FKDR8M467PUQDLNX5JY42ULLE41;
    public static final ForeignKey<PartyUserRecord, UserRecord> FK310GMMHELI8J9JJ5ANW2QMNRA = ForeignKeys0.FK310GMMHELI8J9JJ5ANW2QMNRA;
    public static final ForeignKey<PointRecord, UserRecord> FKR653LUQTDPVNME1QEHLR753IF = ForeignKeys0.FKR653LUQTDPVNME1QEHLR753IF;
    public static final ForeignKey<PremiumRecord, UserRecord> FKCUQ5EVDAVBSBWT2RIU56WSEXL = ForeignKeys0.FKCUQ5EVDAVBSBWT2RIU56WSEXL;
    public static final ForeignKey<QuestRecord, CategoryRecord> FK8O38CSDJ7HT1E8BLO3IMVWDGA = ForeignKeys0.FK8O38CSDJ7HT1E8BLO3IMVWDGA;
    public static final ForeignKey<QuestRecord, UserRecord> FK9GLM6AI8S4XIUJBSUCPGAB31D = ForeignKeys0.FK9GLM6AI8S4XIUJBSUCPGAB31D;
    public static final ForeignKey<QuestReportRecord, QuestRecord> FKONI920KBF1BS1JBC7SALC9K53 = ForeignKeys0.FKONI920KBF1BS1JBC7SALC9K53;
    public static final ForeignKey<QuestReportRecord, UserRecord> FKLX1098F38PYASBE16HYXWOED4 = ForeignKeys0.FKLX1098F38PYASBE16HYXWOED4;
    public static final ForeignKey<QuestReviewRecord, QuestRecord> FKOA8G1SQLAKW01VBFXRVMU6XT = ForeignKeys0.FKOA8G1SQLAKW01VBFXRVMU6XT;
    public static final ForeignKey<QuestReviewRecord, UserRecord> FKP2DHOFAPWR1TTP5CVW19SIT25 = ForeignKeys0.FKP2DHOFAPWR1TTP5CVW19SIT25;
    public static final ForeignKey<StageRecord, QuestRecord> FKN7JEJ65C2NQIV2JKVE9BW9SW4 = ForeignKeys0.FKN7JEJ65C2NQIV2JKVE9BW9SW4;
    public static final ForeignKey<TokenRecord, UserRecord> FKCR55UO5IEX6L1HS2XQP94G2SS = ForeignKeys0.FKCR55UO5IEX6L1HS2XQP94G2SS;
    public static final ForeignKey<UserBadgeRecord, BadgeRecord> FK4ON6HHXOAHTILT08QQX5H23AC = ForeignKeys0.FK4ON6HHXOAHTILT08QQX5H23AC;
    public static final ForeignKey<UserBadgeRecord, UserRecord> FKGEX61AGBF44TMRPANNFIIAFSN = ForeignKeys0.FKGEX61AGBF44TMRPANNFIIAFSN;
    public static final ForeignKey<UserOptionRecord, LanguageRecord> FK300INJW6I3MCW7FVRWO19P7Q5 = ForeignKeys0.FK300INJW6I3MCW7FVRWO19P7Q5;
    public static final ForeignKey<UserOptionRecord, UserRecord> FK2P5OTBGWV6TGF70068RSW2JNH = ForeignKeys0.FK2P5OTBGWV6TGF70068RSW2JNH;
    public static final ForeignKey<UserPartyQuestRecord, PartyQuestRecord> FKN9BGPE63FOBG2NYC49NNR8B0V = ForeignKeys0.FKN9BGPE63FOBG2NYC49NNR8B0V;
    public static final ForeignKey<UserPartyQuestRecord, StageRecord> FKEKB7PXHJX1IE0IDM9VA0QL55K = ForeignKeys0.FKEKB7PXHJX1IE0IDM9VA0QL55K;
    public static final ForeignKey<UserPartyQuestRecord, UserRecord> FKDRS6SEA5S3TBBTUS8F2WVHDEN = ForeignKeys0.FKDRS6SEA5S3TBBTUS8F2WVHDEN;
    public static final ForeignKey<UserQuestRecord, StageRecord> FK977NSU6QESBJIQNOJ44GN7880 = ForeignKeys0.FK977NSU6QESBJIQNOJ44GN7880;
    public static final ForeignKey<UserQuestRecord, UserRecord> FKIBRQXFYCOQIS0E2L8A5SWRCR2 = ForeignKeys0.FKIBRQXFYCOQIS0E2L8A5SWRCR2;
    public static final ForeignKey<UserReportRecord, UserRecord> FKEXPBI245VX37PEBS9ETDEG4G1 = ForeignKeys0.FKEXPBI245VX37PEBS9ETDEG4G1;
    public static final ForeignKey<UserReportRecord, UserRecord> FKGNN173IDLEQCFVAJHRI6YGFDD = ForeignKeys0.FKGNN173IDLEQCFVAJHRI6YGFDD;
    public static final ForeignKey<UserRoleRecord, UserRecord> FKSN0101OEGD6LSFNUMN271CH3I = ForeignKeys0.FKSN0101OEGD6LSFNUMN271CH3I;
    public static final ForeignKey<UserRoleRecord, RoleRecord> FK52VEH3J2TGVKROGJW2I0TUCAC = ForeignKeys0.FK52VEH3J2TGVKROGJW2I0TUCAC;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<BadgeRecord> CONSTRAINT_3 = Internal.createUniqueKey(Badge.BADGE, "CONSTRAINT_3", Badge.BADGE.ID);
        public static final UniqueKey<CategoryRecord> CONSTRAINT_31 = Internal.createUniqueKey(Category.CATEGORY, "CONSTRAINT_31", Category.CATEGORY.ID);
        public static final UniqueKey<ImageRecord> CONSTRAINT_4 = Internal.createUniqueKey(Image.IMAGE, "CONSTRAINT_4", Image.IMAGE.ID);
        public static final UniqueKey<LanguageRecord> CONSTRAINT_C = Internal.createUniqueKey(Language.LANGUAGE, "CONSTRAINT_C", Language.LANGUAGE.ID);
        public static final UniqueKey<LogRecord> CONSTRAINT_1 = Internal.createUniqueKey(Log.LOG, "CONSTRAINT_1", Log.LOG.ID);
        public static final UniqueKey<NotificationRecord> CONSTRAINT_A = Internal.createUniqueKey(Notification.NOTIFICATION, "CONSTRAINT_A", Notification.NOTIFICATION.ID);
        public static final UniqueKey<PartyRecord> CONSTRAINT_48 = Internal.createUniqueKey(Party.PARTY, "CONSTRAINT_48", Party.PARTY.ID);
        public static final UniqueKey<PartyInviteRecord> CONSTRAINT_5 = Internal.createUniqueKey(PartyInvite.PARTY_INVITE, "CONSTRAINT_5", PartyInvite.PARTY_INVITE.ID);
        public static final UniqueKey<PartyQuestRecord> CONSTRAINT_2 = Internal.createUniqueKey(PartyQuest.PARTY_QUEST, "CONSTRAINT_2", PartyQuest.PARTY_QUEST.ID);
        public static final UniqueKey<PartyUserRecord> CONSTRAINT_3B = Internal.createUniqueKey(PartyUser.PARTY_USER, "CONSTRAINT_3B", PartyUser.PARTY_USER.ID);
        public static final UniqueKey<PointRecord> CONSTRAINT_48C = Internal.createUniqueKey(Point.POINT, "CONSTRAINT_48C", Point.POINT.ID);
        public static final UniqueKey<PremiumRecord> CONSTRAINT_17 = Internal.createUniqueKey(Premium.PREMIUM, "CONSTRAINT_17", Premium.PREMIUM.ID);
        public static final UniqueKey<QuestRecord> CONSTRAINT_49 = Internal.createUniqueKey(Quest.QUEST, "CONSTRAINT_49", Quest.QUEST.ID);
        public static final UniqueKey<QuestReportRecord> CONSTRAINT_10 = Internal.createUniqueKey(QuestReport.QUEST_REPORT, "CONSTRAINT_10", QuestReport.QUEST_REPORT.ID);
        public static final UniqueKey<QuestReviewRecord> CONSTRAINT_105 = Internal.createUniqueKey(QuestReview.QUEST_REVIEW, "CONSTRAINT_105", QuestReview.QUEST_REVIEW.ID);
        public static final UniqueKey<QuestReviewRecord> UKTIP5DD0129ALBKCV3KRX41IBO = Internal.createUniqueKey(QuestReview.QUEST_REVIEW, "UKTIP5DD0129ALBKCV3KRX41IBO", QuestReview.QUEST_REVIEW.USER_ID, QuestReview.QUEST_REVIEW.QUEST_ID);
        public static final UniqueKey<RoleRecord> CONSTRAINT_26 = Internal.createUniqueKey(Role.ROLE, "CONSTRAINT_26", Role.ROLE.ID);
        public static final UniqueKey<StageRecord> CONSTRAINT_4B = Internal.createUniqueKey(Stage.STAGE, "CONSTRAINT_4B", Stage.STAGE.ID);
        public static final UniqueKey<TokenRecord> CONSTRAINT_4C = Internal.createUniqueKey(Token.TOKEN, "CONSTRAINT_4C", Token.TOKEN.ID);
        public static final UniqueKey<UserRecord> CONSTRAINT_27 = Internal.createUniqueKey(User.USER, "CONSTRAINT_27", User.USER.ID);
        public static final UniqueKey<UserRecord> UK_OSO07PUDW19E66BS4YP8HWPUX = Internal.createUniqueKey(User.USER, "UK_OSO07PUDW19E66BS4YP8HWPUX", User.USER.EMAIL);
        public static final UniqueKey<UserRecord> UK_41DMWQT0G1WFLBC7PNQHER1A = Internal.createUniqueKey(User.USER, "UK_41DMWQT0G1WFLBC7PNQHER1A", User.USER.NICK_NAME);
        public static final UniqueKey<UserBadgeRecord> CONSTRAINT_C5 = Internal.createUniqueKey(UserBadge.USER_BADGE, "CONSTRAINT_C5", UserBadge.USER_BADGE.ID);
        public static final UniqueKey<UserOptionRecord> CONSTRAINT_D = Internal.createUniqueKey(UserOption.USER_OPTION, "CONSTRAINT_D", UserOption.USER_OPTION.ID);
        public static final UniqueKey<UserPartyQuestRecord> CONSTRAINT_55 = Internal.createUniqueKey(UserPartyQuest.USER_PARTY_QUEST, "CONSTRAINT_55", UserPartyQuest.USER_PARTY_QUEST.ID);
        public static final UniqueKey<UserQuestRecord> CONSTRAINT_C6 = Internal.createUniqueKey(UserQuest.USER_QUEST, "CONSTRAINT_C6", UserQuest.USER_QUEST.ID);
        public static final UniqueKey<UserReportRecord> CONSTRAINT_11 = Internal.createUniqueKey(UserReport.USER_REPORT, "CONSTRAINT_11", UserReport.USER_REPORT.ID);
        public static final UniqueKey<UserReportRecord> UKD8H5NIRV4QEVOSRD38T6ATCD6 = Internal.createUniqueKey(UserReport.USER_REPORT, "UKD8H5NIRV4QEVOSRD38T6ATCD6", UserReport.USER_REPORT.REPORTED, UserReport.USER_REPORT.COMPLAINANT);
        public static final UniqueKey<UserRoleRecord> CONSTRAINT_B = Internal.createUniqueKey(UserRole.USER_ROLE, "CONSTRAINT_B", UserRole.USER_ROLE.USER_ID, UserRole.USER_ROLE.ROLE_ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<ImageRecord, QuestRecord> FK4RXXT2CJB76UV4J43SL3QAY2H = Internal.createForeignKey(com.geoly.app.jooq.Keys.CONSTRAINT_49, Image.IMAGE, "FK4RXXT2CJB76UV4J43SL3QAY2H", Image.IMAGE.QUEST_ID);
        public static final ForeignKey<NotificationRecord, UserRecord> FK16C2APDKEL73R81ED2DPWV0A2 = Internal.createForeignKey(com.geoly.app.jooq.Keys.CONSTRAINT_27, Notification.NOTIFICATION, "FK16C2APDKEL73R81ED2DPWV0A2", Notification.NOTIFICATION.USER_ID);
        public static final ForeignKey<PartyRecord, UserRecord> FKQFWC76LQ1GWTEVTA6KHS862RK = Internal.createForeignKey(com.geoly.app.jooq.Keys.CONSTRAINT_27, Party.PARTY, "FKQFWC76LQ1GWTEVTA6KHS862RK", Party.PARTY.USER_ID);
        public static final ForeignKey<PartyInviteRecord, PartyRecord> FKECYTUNFMMOIEEEIW7NAQ57UYE = Internal.createForeignKey(com.geoly.app.jooq.Keys.CONSTRAINT_48, PartyInvite.PARTY_INVITE, "FKECYTUNFMMOIEEEIW7NAQ57UYE", PartyInvite.PARTY_INVITE.PARTY_ID);
        public static final ForeignKey<PartyInviteRecord, UserRecord> FK5H11DMN0OV3Y30CYVN01NOUR3 = Internal.createForeignKey(com.geoly.app.jooq.Keys.CONSTRAINT_27, PartyInvite.PARTY_INVITE, "FK5H11DMN0OV3Y30CYVN01NOUR3", PartyInvite.PARTY_INVITE.USER_ID);
        public static final ForeignKey<PartyQuestRecord, PartyRecord> FK4BFMT3TPKS38SN4GW97VYHEM3 = Internal.createForeignKey(com.geoly.app.jooq.Keys.CONSTRAINT_48, PartyQuest.PARTY_QUEST, "FK4BFMT3TPKS38SN4GW97VYHEM3", PartyQuest.PARTY_QUEST.PARTY_ID);
        public static final ForeignKey<PartyQuestRecord, QuestRecord> FKHFLFH9KMNL4BFFJFQH57IGR76 = Internal.createForeignKey(com.geoly.app.jooq.Keys.CONSTRAINT_49, PartyQuest.PARTY_QUEST, "FKHFLFH9KMNL4BFFJFQH57IGR76", PartyQuest.PARTY_QUEST.QUEST_ID);
        public static final ForeignKey<PartyUserRecord, PartyRecord> FKDR8M467PUQDLNX5JY42ULLE41 = Internal.createForeignKey(com.geoly.app.jooq.Keys.CONSTRAINT_48, PartyUser.PARTY_USER, "FKDR8M467PUQDLNX5JY42ULLE41", PartyUser.PARTY_USER.PARTY_ID);
        public static final ForeignKey<PartyUserRecord, UserRecord> FK310GMMHELI8J9JJ5ANW2QMNRA = Internal.createForeignKey(com.geoly.app.jooq.Keys.CONSTRAINT_27, PartyUser.PARTY_USER, "FK310GMMHELI8J9JJ5ANW2QMNRA", PartyUser.PARTY_USER.USER_ID);
        public static final ForeignKey<PointRecord, UserRecord> FKR653LUQTDPVNME1QEHLR753IF = Internal.createForeignKey(com.geoly.app.jooq.Keys.CONSTRAINT_27, Point.POINT, "FKR653LUQTDPVNME1QEHLR753IF", Point.POINT.USER_ID);
        public static final ForeignKey<PremiumRecord, UserRecord> FKCUQ5EVDAVBSBWT2RIU56WSEXL = Internal.createForeignKey(com.geoly.app.jooq.Keys.CONSTRAINT_27, Premium.PREMIUM, "FKCUQ5EVDAVBSBWT2RIU56WSEXL", Premium.PREMIUM.USER_ID);
        public static final ForeignKey<QuestRecord, CategoryRecord> FK8O38CSDJ7HT1E8BLO3IMVWDGA = Internal.createForeignKey(com.geoly.app.jooq.Keys.CONSTRAINT_31, Quest.QUEST, "FK8O38CSDJ7HT1E8BLO3IMVWDGA", Quest.QUEST.CATEGORY_ID);
        public static final ForeignKey<QuestRecord, UserRecord> FK9GLM6AI8S4XIUJBSUCPGAB31D = Internal.createForeignKey(com.geoly.app.jooq.Keys.CONSTRAINT_27, Quest.QUEST, "FK9GLM6AI8S4XIUJBSUCPGAB31D", Quest.QUEST.USER_ID);
        public static final ForeignKey<QuestReportRecord, QuestRecord> FKONI920KBF1BS1JBC7SALC9K53 = Internal.createForeignKey(com.geoly.app.jooq.Keys.CONSTRAINT_49, QuestReport.QUEST_REPORT, "FKONI920KBF1BS1JBC7SALC9K53", QuestReport.QUEST_REPORT.QUEST_ID);
        public static final ForeignKey<QuestReportRecord, UserRecord> FKLX1098F38PYASBE16HYXWOED4 = Internal.createForeignKey(com.geoly.app.jooq.Keys.CONSTRAINT_27, QuestReport.QUEST_REPORT, "FKLX1098F38PYASBE16HYXWOED4", QuestReport.QUEST_REPORT.USER_ID);
        public static final ForeignKey<QuestReviewRecord, QuestRecord> FKOA8G1SQLAKW01VBFXRVMU6XT = Internal.createForeignKey(com.geoly.app.jooq.Keys.CONSTRAINT_49, QuestReview.QUEST_REVIEW, "FKOA8G1SQLAKW01VBFXRVMU6XT", QuestReview.QUEST_REVIEW.QUEST_ID);
        public static final ForeignKey<QuestReviewRecord, UserRecord> FKP2DHOFAPWR1TTP5CVW19SIT25 = Internal.createForeignKey(com.geoly.app.jooq.Keys.CONSTRAINT_27, QuestReview.QUEST_REVIEW, "FKP2DHOFAPWR1TTP5CVW19SIT25", QuestReview.QUEST_REVIEW.USER_ID);
        public static final ForeignKey<StageRecord, QuestRecord> FKN7JEJ65C2NQIV2JKVE9BW9SW4 = Internal.createForeignKey(com.geoly.app.jooq.Keys.CONSTRAINT_49, Stage.STAGE, "FKN7JEJ65C2NQIV2JKVE9BW9SW4", Stage.STAGE.QUEST_ID);
        public static final ForeignKey<TokenRecord, UserRecord> FKCR55UO5IEX6L1HS2XQP94G2SS = Internal.createForeignKey(com.geoly.app.jooq.Keys.CONSTRAINT_27, Token.TOKEN, "FKCR55UO5IEX6L1HS2XQP94G2SS", Token.TOKEN.USER_ID);
        public static final ForeignKey<UserBadgeRecord, BadgeRecord> FK4ON6HHXOAHTILT08QQX5H23AC = Internal.createForeignKey(com.geoly.app.jooq.Keys.CONSTRAINT_3, UserBadge.USER_BADGE, "FK4ON6HHXOAHTILT08QQX5H23AC", UserBadge.USER_BADGE.BADGE_ID);
        public static final ForeignKey<UserBadgeRecord, UserRecord> FKGEX61AGBF44TMRPANNFIIAFSN = Internal.createForeignKey(com.geoly.app.jooq.Keys.CONSTRAINT_27, UserBadge.USER_BADGE, "FKGEX61AGBF44TMRPANNFIIAFSN", UserBadge.USER_BADGE.USER_ID);
        public static final ForeignKey<UserOptionRecord, LanguageRecord> FK300INJW6I3MCW7FVRWO19P7Q5 = Internal.createForeignKey(com.geoly.app.jooq.Keys.CONSTRAINT_C, UserOption.USER_OPTION, "FK300INJW6I3MCW7FVRWO19P7Q5", UserOption.USER_OPTION.LANGUAGE_ID);
        public static final ForeignKey<UserOptionRecord, UserRecord> FK2P5OTBGWV6TGF70068RSW2JNH = Internal.createForeignKey(com.geoly.app.jooq.Keys.CONSTRAINT_27, UserOption.USER_OPTION, "FK2P5OTBGWV6TGF70068RSW2JNH", UserOption.USER_OPTION.USER_ID);
        public static final ForeignKey<UserPartyQuestRecord, PartyQuestRecord> FKN9BGPE63FOBG2NYC49NNR8B0V = Internal.createForeignKey(com.geoly.app.jooq.Keys.CONSTRAINT_2, UserPartyQuest.USER_PARTY_QUEST, "FKN9BGPE63FOBG2NYC49NNR8B0V", UserPartyQuest.USER_PARTY_QUEST.PARTY_QUEST_ID);
        public static final ForeignKey<UserPartyQuestRecord, StageRecord> FKEKB7PXHJX1IE0IDM9VA0QL55K = Internal.createForeignKey(com.geoly.app.jooq.Keys.CONSTRAINT_4B, UserPartyQuest.USER_PARTY_QUEST, "FKEKB7PXHJX1IE0IDM9VA0QL55K", UserPartyQuest.USER_PARTY_QUEST.STAGE_ID);
        public static final ForeignKey<UserPartyQuestRecord, UserRecord> FKDRS6SEA5S3TBBTUS8F2WVHDEN = Internal.createForeignKey(com.geoly.app.jooq.Keys.CONSTRAINT_27, UserPartyQuest.USER_PARTY_QUEST, "FKDRS6SEA5S3TBBTUS8F2WVHDEN", UserPartyQuest.USER_PARTY_QUEST.USER_ID);
        public static final ForeignKey<UserQuestRecord, StageRecord> FK977NSU6QESBJIQNOJ44GN7880 = Internal.createForeignKey(com.geoly.app.jooq.Keys.CONSTRAINT_4B, UserQuest.USER_QUEST, "FK977NSU6QESBJIQNOJ44GN7880", UserQuest.USER_QUEST.STAGE_ID);
        public static final ForeignKey<UserQuestRecord, UserRecord> FKIBRQXFYCOQIS0E2L8A5SWRCR2 = Internal.createForeignKey(com.geoly.app.jooq.Keys.CONSTRAINT_27, UserQuest.USER_QUEST, "FKIBRQXFYCOQIS0E2L8A5SWRCR2", UserQuest.USER_QUEST.USER_ID);
        public static final ForeignKey<UserReportRecord, UserRecord> FKEXPBI245VX37PEBS9ETDEG4G1 = Internal.createForeignKey(com.geoly.app.jooq.Keys.CONSTRAINT_27, UserReport.USER_REPORT, "FKEXPBI245VX37PEBS9ETDEG4G1", UserReport.USER_REPORT.COMPLAINANT);
        public static final ForeignKey<UserReportRecord, UserRecord> FKGNN173IDLEQCFVAJHRI6YGFDD = Internal.createForeignKey(com.geoly.app.jooq.Keys.CONSTRAINT_27, UserReport.USER_REPORT, "FKGNN173IDLEQCFVAJHRI6YGFDD", UserReport.USER_REPORT.REPORTED);
        public static final ForeignKey<UserRoleRecord, UserRecord> FKSN0101OEGD6LSFNUMN271CH3I = Internal.createForeignKey(com.geoly.app.jooq.Keys.CONSTRAINT_27, UserRole.USER_ROLE, "FKSN0101OEGD6LSFNUMN271CH3I", UserRole.USER_ROLE.USER_ID);
        public static final ForeignKey<UserRoleRecord, RoleRecord> FK52VEH3J2TGVKROGJW2I0TUCAC = Internal.createForeignKey(com.geoly.app.jooq.Keys.CONSTRAINT_26, UserRole.USER_ROLE, "FK52VEH3J2TGVKROGJW2I0TUCAC", UserRole.USER_ROLE.ROLE_ID);
    }
}
