/*
 * This file is generated by jOOQ.
 */
package com.geoly.app.jooq;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in geoly
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>geoly.HIBERNATE_SEQUENCE</code>
     */
    public static final Sequence<Long> HIBERNATE_SEQUENCE = new SequenceImpl<Long>("HIBERNATE_SEQUENCE", Geoly.GEOLY, org.jooq.impl.SQLDataType.BIGINT);
}
