/*
 * This file is generated by jOOQ.
 */
package com.geoly.app.jooq.tables.records;


import com.geoly.app.jooq.tables.PartyQuest;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PartyQuestRecord extends UpdatableRecordImpl<PartyQuestRecord> implements Record4<Integer, Byte, Integer, Integer> {

    private static final long serialVersionUID = 625683369;

    /**
     * Setter for <code>geoly.PARTY_QUEST.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>geoly.PARTY_QUEST.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>geoly.PARTY_QUEST.ACTIVE</code>.
     */
    public void setActive(Byte value) {
        set(1, value);
    }

    /**
     * Getter for <code>geoly.PARTY_QUEST.ACTIVE</code>.
     */
    public Byte getActive() {
        return (Byte) get(1);
    }

    /**
     * Setter for <code>geoly.PARTY_QUEST.PARTY_ID</code>.
     */
    public void setPartyId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>geoly.PARTY_QUEST.PARTY_ID</code>.
     */
    public Integer getPartyId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>geoly.PARTY_QUEST.QUEST_ID</code>.
     */
    public void setQuestId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>geoly.PARTY_QUEST.QUEST_ID</code>.
     */
    public Integer getQuestId() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Byte, Integer, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Byte, Integer, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return PartyQuest.PARTY_QUEST.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field2() {
        return PartyQuest.PARTY_QUEST.ACTIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return PartyQuest.PARTY_QUEST.PARTY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return PartyQuest.PARTY_QUEST.QUEST_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component2() {
        return getActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getPartyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getQuestId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value2() {
        return getActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getPartyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getQuestId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PartyQuestRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PartyQuestRecord value2(Byte value) {
        setActive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PartyQuestRecord value3(Integer value) {
        setPartyId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PartyQuestRecord value4(Integer value) {
        setQuestId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PartyQuestRecord values(Integer value1, Byte value2, Integer value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PartyQuestRecord
     */
    public PartyQuestRecord() {
        super(PartyQuest.PARTY_QUEST);
    }

    /**
     * Create a detached, initialised PartyQuestRecord
     */
    public PartyQuestRecord(Integer id, Byte active, Integer partyId, Integer questId) {
        super(PartyQuest.PARTY_QUEST);

        set(0, id);
        set(1, active);
        set(2, partyId);
        set(3, questId);
    }
}
