/*
 * This file is generated by jOOQ.
 */
package com.geoly.app.jooq.tables.records;


import com.geoly.app.jooq.tables.Premium;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PremiumRecord extends UpdatableRecordImpl<PremiumRecord> implements Record6<Integer, String, Timestamp, Timestamp, String, Integer> {

    private static final long serialVersionUID = 590094875;

    /**
     * Setter for <code>geoly.PREMIUM.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>geoly.PREMIUM.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>geoly.PREMIUM.AGREEMENT_ID</code>.
     */
    public void setAgreementId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>geoly.PREMIUM.AGREEMENT_ID</code>.
     */
    public String getAgreementId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>geoly.PREMIUM.END_AT</code>.
     */
    public void setEndAt(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>geoly.PREMIUM.END_AT</code>.
     */
    public Timestamp getEndAt() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>geoly.PREMIUM.START_AT</code>.
     */
    public void setStartAt(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>geoly.PREMIUM.START_AT</code>.
     */
    public Timestamp getStartAt() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>geoly.PREMIUM.STATE</code>.
     */
    public void setState(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>geoly.PREMIUM.STATE</code>.
     */
    public String getState() {
        return (String) get(4);
    }

    /**
     * Setter for <code>geoly.PREMIUM.USER_ID</code>.
     */
    public void setUserId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>geoly.PREMIUM.USER_ID</code>.
     */
    public Integer getUserId() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, Timestamp, Timestamp, String, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, Timestamp, Timestamp, String, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Premium.PREMIUM.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Premium.PREMIUM.AGREEMENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return Premium.PREMIUM.END_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return Premium.PREMIUM.START_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Premium.PREMIUM.STATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Premium.PREMIUM.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getAgreementId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getEndAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getStartAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getAgreementId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getEndAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getStartAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PremiumRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PremiumRecord value2(String value) {
        setAgreementId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PremiumRecord value3(Timestamp value) {
        setEndAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PremiumRecord value4(Timestamp value) {
        setStartAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PremiumRecord value5(String value) {
        setState(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PremiumRecord value6(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PremiumRecord values(Integer value1, String value2, Timestamp value3, Timestamp value4, String value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PremiumRecord
     */
    public PremiumRecord() {
        super(Premium.PREMIUM);
    }

    /**
     * Create a detached, initialised PremiumRecord
     */
    public PremiumRecord(Integer id, String agreementId, Timestamp endAt, Timestamp startAt, String state, Integer userId) {
        super(Premium.PREMIUM);

        set(0, id);
        set(1, agreementId);
        set(2, endAt);
        set(3, startAt);
        set(4, state);
        set(5, userId);
    }
}
