/*
 * This file is generated by jOOQ.
 */
package com.geoly.app.jooq.tables.records;


import com.geoly.app.jooq.tables.Premium;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PremiumRecord extends UpdatableRecordImpl<PremiumRecord> implements Record5<Integer, Timestamp, Timestamp, Integer, Integer> {

    private static final long serialVersionUID = -1341018171;

    /**
     * Setter for <code>geoly.PREMIUM.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>geoly.PREMIUM.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>geoly.PREMIUM.END_AT</code>.
     */
    public void setEndAt(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>geoly.PREMIUM.END_AT</code>.
     */
    public Timestamp getEndAt() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>geoly.PREMIUM.START_AT</code>.
     */
    public void setStartAt(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>geoly.PREMIUM.START_AT</code>.
     */
    public Timestamp getStartAt() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>geoly.PREMIUM.TRANSACTION_ID</code>.
     */
    public void setTransactionId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>geoly.PREMIUM.TRANSACTION_ID</code>.
     */
    public Integer getTransactionId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>geoly.PREMIUM.USER_ID</code>.
     */
    public void setUserId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>geoly.PREMIUM.USER_ID</code>.
     */
    public Integer getUserId() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Timestamp, Timestamp, Integer, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Timestamp, Timestamp, Integer, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Premium.PREMIUM.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return Premium.PREMIUM.END_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return Premium.PREMIUM.START_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Premium.PREMIUM.TRANSACTION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Premium.PREMIUM.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component2() {
        return getEndAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getStartAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getTransactionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getEndAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getStartAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getTransactionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PremiumRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PremiumRecord value2(Timestamp value) {
        setEndAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PremiumRecord value3(Timestamp value) {
        setStartAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PremiumRecord value4(Integer value) {
        setTransactionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PremiumRecord value5(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PremiumRecord values(Integer value1, Timestamp value2, Timestamp value3, Integer value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PremiumRecord
     */
    public PremiumRecord() {
        super(Premium.PREMIUM);
    }

    /**
     * Create a detached, initialised PremiumRecord
     */
    public PremiumRecord(Integer id, Timestamp endAt, Timestamp startAt, Integer transactionId, Integer userId) {
        super(Premium.PREMIUM);

        set(0, id);
        set(1, endAt);
        set(2, startAt);
        set(3, transactionId);
        set(4, userId);
    }
}
