/*
 * This file is generated by jOOQ.
 */
package com.geoly.app.jooq.tables.records;


import com.geoly.app.jooq.tables.QuestReport;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QuestReportRecord extends UpdatableRecordImpl<QuestReportRecord> implements Record6<Integer, Timestamp, String, Byte, Integer, Integer> {

    private static final long serialVersionUID = 1406876606;

    /**
     * Setter for <code>geoly.QUEST_REPORT.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>geoly.QUEST_REPORT.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>geoly.QUEST_REPORT.CREATED_AT</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>geoly.QUEST_REPORT.CREATED_AT</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>geoly.QUEST_REPORT.REASON</code>.
     */
    public void setReason(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>geoly.QUEST_REPORT.REASON</code>.
     */
    public String getReason() {
        return (String) get(2);
    }

    /**
     * Setter for <code>geoly.QUEST_REPORT.SOLVED</code>.
     */
    public void setSolved(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>geoly.QUEST_REPORT.SOLVED</code>.
     */
    public Byte getSolved() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>geoly.QUEST_REPORT.QUEST_ID</code>.
     */
    public void setQuestId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>geoly.QUEST_REPORT.QUEST_ID</code>.
     */
    public Integer getQuestId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>geoly.QUEST_REPORT.USER_ID</code>.
     */
    public void setUserId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>geoly.QUEST_REPORT.USER_ID</code>.
     */
    public Integer getUserId() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Timestamp, String, Byte, Integer, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Timestamp, String, Byte, Integer, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return QuestReport.QUEST_REPORT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return QuestReport.QUEST_REPORT.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return QuestReport.QUEST_REPORT.REASON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field4() {
        return QuestReport.QUEST_REPORT.SOLVED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return QuestReport.QUEST_REPORT.QUEST_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return QuestReport.QUEST_REPORT.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component2() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getReason();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component4() {
        return getSolved();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getQuestId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getReason();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value4() {
        return getSolved();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getQuestId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuestReportRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuestReportRecord value2(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuestReportRecord value3(String value) {
        setReason(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuestReportRecord value4(Byte value) {
        setSolved(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuestReportRecord value5(Integer value) {
        setQuestId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuestReportRecord value6(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuestReportRecord values(Integer value1, Timestamp value2, String value3, Byte value4, Integer value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached QuestReportRecord
     */
    public QuestReportRecord() {
        super(QuestReport.QUEST_REPORT);
    }

    /**
     * Create a detached, initialised QuestReportRecord
     */
    public QuestReportRecord(Integer id, Timestamp createdAt, String reason, Byte solved, Integer questId, Integer userId) {
        super(QuestReport.QUEST_REPORT);

        set(0, id);
        set(1, createdAt);
        set(2, reason);
        set(3, solved);
        set(4, questId);
        set(5, userId);
    }
}
