/*
 * This file is generated by jOOQ.
 */
package com.geoly.app.jooq.tables.records;


import com.geoly.app.jooq.tables.QuestReview;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QuestReviewRecord extends UpdatableRecordImpl<QuestReviewRecord> implements Record6<Integer, Timestamp, Byte, String, Integer, Integer> {

    private static final long serialVersionUID = 1100485873;

    /**
     * Setter for <code>geoly.QUEST_REVIEW.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>geoly.QUEST_REVIEW.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>geoly.QUEST_REVIEW.CREATED_AT</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>geoly.QUEST_REVIEW.CREATED_AT</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>geoly.QUEST_REVIEW.REVIEW</code>.
     */
    public void setReview(Byte value) {
        set(2, value);
    }

    /**
     * Getter for <code>geoly.QUEST_REVIEW.REVIEW</code>.
     */
    public Byte getReview() {
        return (Byte) get(2);
    }

    /**
     * Setter for <code>geoly.QUEST_REVIEW.REVIEW_TEXT</code>.
     */
    public void setReviewText(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>geoly.QUEST_REVIEW.REVIEW_TEXT</code>.
     */
    public String getReviewText() {
        return (String) get(3);
    }

    /**
     * Setter for <code>geoly.QUEST_REVIEW.QUEST_ID</code>.
     */
    public void setQuestId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>geoly.QUEST_REVIEW.QUEST_ID</code>.
     */
    public Integer getQuestId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>geoly.QUEST_REVIEW.USER_ID</code>.
     */
    public void setUserId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>geoly.QUEST_REVIEW.USER_ID</code>.
     */
    public Integer getUserId() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Timestamp, Byte, String, Integer, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Timestamp, Byte, String, Integer, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return QuestReview.QUEST_REVIEW.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return QuestReview.QUEST_REVIEW.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field3() {
        return QuestReview.QUEST_REVIEW.REVIEW;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return QuestReview.QUEST_REVIEW.REVIEW_TEXT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return QuestReview.QUEST_REVIEW.QUEST_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return QuestReview.QUEST_REVIEW.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component2() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component3() {
        return getReview();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getReviewText();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getQuestId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value3() {
        return getReview();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getReviewText();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getQuestId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuestReviewRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuestReviewRecord value2(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuestReviewRecord value3(Byte value) {
        setReview(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuestReviewRecord value4(String value) {
        setReviewText(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuestReviewRecord value5(Integer value) {
        setQuestId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuestReviewRecord value6(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuestReviewRecord values(Integer value1, Timestamp value2, Byte value3, String value4, Integer value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached QuestReviewRecord
     */
    public QuestReviewRecord() {
        super(QuestReview.QUEST_REVIEW);
    }

    /**
     * Create a detached, initialised QuestReviewRecord
     */
    public QuestReviewRecord(Integer id, Timestamp createdAt, Byte review, String reviewText, Integer questId, Integer userId) {
        super(QuestReview.QUEST_REVIEW);

        set(0, id);
        set(1, createdAt);
        set(2, review);
        set(3, reviewText);
        set(4, questId);
        set(5, userId);
    }
}
