/*
 * This file is generated by jOOQ.
 */
package com.geoly.app.jooq.tables.records;


import com.geoly.app.jooq.tables.Stage;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StageRecord extends UpdatableRecordImpl<StageRecord> implements Record11<Integer, String, String, String, Double, Double, String, String, String, String, Integer> {

    private static final long serialVersionUID = -1887963257;

    /**
     * Setter for <code>geoly.STAGE.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>geoly.STAGE.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>geoly.STAGE.ADVISE</code>.
     */
    public void setAdvise(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>geoly.STAGE.ADVISE</code>.
     */
    public String getAdvise() {
        return (String) get(1);
    }

    /**
     * Setter for <code>geoly.STAGE.ANSWER</code>.
     */
    public void setAnswer(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>geoly.STAGE.ANSWER</code>.
     */
    public String getAnswer() {
        return (String) get(2);
    }

    /**
     * Setter for <code>geoly.STAGE.ANSWERS_LIST</code>.
     */
    public void setAnswersList(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>geoly.STAGE.ANSWERS_LIST</code>.
     */
    public String getAnswersList() {
        return (String) get(3);
    }

    /**
     * Setter for <code>geoly.STAGE.LATITUDE</code>.
     */
    public void setLatitude(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>geoly.STAGE.LATITUDE</code>.
     */
    public Double getLatitude() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>geoly.STAGE.LONGITUDE</code>.
     */
    public void setLongitude(Double value) {
        set(5, value);
    }

    /**
     * Getter for <code>geoly.STAGE.LONGITUDE</code>.
     */
    public Double getLongitude() {
        return (Double) get(5);
    }

    /**
     * Setter for <code>geoly.STAGE.NOTE</code>.
     */
    public void setNote(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>geoly.STAGE.NOTE</code>.
     */
    public String getNote() {
        return (String) get(6);
    }

    /**
     * Setter for <code>geoly.STAGE.QR_CODE_URL</code>.
     */
    public void setQrCodeUrl(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>geoly.STAGE.QR_CODE_URL</code>.
     */
    public String getQrCodeUrl() {
        return (String) get(7);
    }

    /**
     * Setter for <code>geoly.STAGE.QUESTION</code>.
     */
    public void setQuestion(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>geoly.STAGE.QUESTION</code>.
     */
    public String getQuestion() {
        return (String) get(8);
    }

    /**
     * Setter for <code>geoly.STAGE.TYPE</code>.
     */
    public void setType(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>geoly.STAGE.TYPE</code>.
     */
    public String getType() {
        return (String) get(9);
    }

    /**
     * Setter for <code>geoly.STAGE.QUEST_ID</code>.
     */
    public void setQuestId(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>geoly.STAGE.QUEST_ID</code>.
     */
    public Integer getQuestId() {
        return (Integer) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Integer, String, String, String, Double, Double, String, String, String, String, Integer> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Integer, String, String, String, Double, Double, String, String, String, String, Integer> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Stage.STAGE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Stage.STAGE.ADVISE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Stage.STAGE.ANSWER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Stage.STAGE.ANSWERS_LIST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field5() {
        return Stage.STAGE.LATITUDE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field6() {
        return Stage.STAGE.LONGITUDE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Stage.STAGE.NOTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Stage.STAGE.QR_CODE_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Stage.STAGE.QUESTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Stage.STAGE.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return Stage.STAGE.QUEST_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getAdvise();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getAnswer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getAnswersList();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component5() {
        return getLatitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component6() {
        return getLongitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getNote();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getQrCodeUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getQuestion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component11() {
        return getQuestId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getAdvise();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getAnswer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getAnswersList();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value5() {
        return getLatitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value6() {
        return getLongitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getNote();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getQrCodeUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getQuestion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getQuestId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StageRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StageRecord value2(String value) {
        setAdvise(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StageRecord value3(String value) {
        setAnswer(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StageRecord value4(String value) {
        setAnswersList(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StageRecord value5(Double value) {
        setLatitude(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StageRecord value6(Double value) {
        setLongitude(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StageRecord value7(String value) {
        setNote(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StageRecord value8(String value) {
        setQrCodeUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StageRecord value9(String value) {
        setQuestion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StageRecord value10(String value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StageRecord value11(Integer value) {
        setQuestId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StageRecord values(Integer value1, String value2, String value3, String value4, Double value5, Double value6, String value7, String value8, String value9, String value10, Integer value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StageRecord
     */
    public StageRecord() {
        super(Stage.STAGE);
    }

    /**
     * Create a detached, initialised StageRecord
     */
    public StageRecord(Integer id, String advise, String answer, String answersList, Double latitude, Double longitude, String note, String qrCodeUrl, String question, String type, Integer questId) {
        super(Stage.STAGE);

        set(0, id);
        set(1, advise);
        set(2, answer);
        set(3, answersList);
        set(4, latitude);
        set(5, longitude);
        set(6, note);
        set(7, qrCodeUrl);
        set(8, question);
        set(9, type);
        set(10, questId);
    }
}
