/*
 * This file is generated by jOOQ.
 */
package com.geoly.app.jooq.tables.records;


import com.geoly.app.jooq.tables.UserQuest;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserQuestRecord extends UpdatableRecordImpl<UserQuestRecord> implements Record8<Integer, Byte, Timestamp, String, Timestamp, Integer, Integer, Integer> {

    private static final long serialVersionUID = 597656687;

    /**
     * Setter for <code>geoly.USER_QUEST.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>geoly.USER_QUEST.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>geoly.USER_QUEST.ADVISE_USED</code>.
     */
    public void setAdviseUsed(Byte value) {
        set(1, value);
    }

    /**
     * Getter for <code>geoly.USER_QUEST.ADVISE_USED</code>.
     */
    public Byte getAdviseUsed() {
        return (Byte) get(1);
    }

    /**
     * Setter for <code>geoly.USER_QUEST.CREATED_AT</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>geoly.USER_QUEST.CREATED_AT</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>geoly.USER_QUEST.STATUS</code>.
     */
    public void setStatus(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>geoly.USER_QUEST.STATUS</code>.
     */
    public String getStatus() {
        return (String) get(3);
    }

    /**
     * Setter for <code>geoly.USER_QUEST.UPDATED_AT</code>.
     */
    public void setUpdatedAt(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>geoly.USER_QUEST.UPDATED_AT</code>.
     */
    public Timestamp getUpdatedAt() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>geoly.USER_QUEST.WRONG_ANSWERS</code>.
     */
    public void setWrongAnswers(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>geoly.USER_QUEST.WRONG_ANSWERS</code>.
     */
    public Integer getWrongAnswers() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>geoly.USER_QUEST.STAGE_ID</code>.
     */
    public void setStageId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>geoly.USER_QUEST.STAGE_ID</code>.
     */
    public Integer getStageId() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>geoly.USER_QUEST.USER_ID</code>.
     */
    public void setUserId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>geoly.USER_QUEST.USER_ID</code>.
     */
    public Integer getUserId() {
        return (Integer) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, Byte, Timestamp, String, Timestamp, Integer, Integer, Integer> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, Byte, Timestamp, String, Timestamp, Integer, Integer, Integer> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return UserQuest.USER_QUEST.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field2() {
        return UserQuest.USER_QUEST.ADVISE_USED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return UserQuest.USER_QUEST.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return UserQuest.USER_QUEST.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return UserQuest.USER_QUEST.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return UserQuest.USER_QUEST.WRONG_ANSWERS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return UserQuest.USER_QUEST.STAGE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return UserQuest.USER_QUEST.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component2() {
        return getAdviseUsed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getWrongAnswers();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getStageId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value2() {
        return getAdviseUsed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getWrongAnswers();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getStageId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserQuestRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserQuestRecord value2(Byte value) {
        setAdviseUsed(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserQuestRecord value3(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserQuestRecord value4(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserQuestRecord value5(Timestamp value) {
        setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserQuestRecord value6(Integer value) {
        setWrongAnswers(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserQuestRecord value7(Integer value) {
        setStageId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserQuestRecord value8(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserQuestRecord values(Integer value1, Byte value2, Timestamp value3, String value4, Timestamp value5, Integer value6, Integer value7, Integer value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserQuestRecord
     */
    public UserQuestRecord() {
        super(UserQuest.USER_QUEST);
    }

    /**
     * Create a detached, initialised UserQuestRecord
     */
    public UserQuestRecord(Integer id, Byte adviseUsed, Timestamp createdAt, String status, Timestamp updatedAt, Integer wrongAnswers, Integer stageId, Integer userId) {
        super(UserQuest.USER_QUEST);

        set(0, id);
        set(1, adviseUsed);
        set(2, createdAt);
        set(3, status);
        set(4, updatedAt);
        set(5, wrongAnswers);
        set(6, stageId);
        set(7, userId);
    }
}
