/*
 * This file is generated by jOOQ.
 */
package com.geoly.app.jooq.tables.records;


import com.geoly.app.jooq.tables.User;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRecord extends UpdatableRecordImpl<UserRecord> implements Record11<Integer, String, Byte, String, Timestamp, Timestamp, String, String, String, String, Byte> {

    private static final long serialVersionUID = -1122320047;

    /**
     * Setter for <code>geoly.USER.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>geoly.USER.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>geoly.USER.ABOUT</code>.
     */
    public void setAbout(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>geoly.USER.ABOUT</code>.
     */
    public String getAbout() {
        return (String) get(1);
    }

    /**
     * Setter for <code>geoly.USER.ACTIVE</code>.
     */
    public void setActive(Byte value) {
        set(2, value);
    }

    /**
     * Getter for <code>geoly.USER.ACTIVE</code>.
     */
    public Byte getActive() {
        return (Byte) get(2);
    }

    /**
     * Setter for <code>geoly.USER.ADDRESS</code>.
     */
    public void setAddress(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>geoly.USER.ADDRESS</code>.
     */
    public String getAddress() {
        return (String) get(3);
    }

    /**
     * Setter for <code>geoly.USER.ADDRESS_UPDATE</code>.
     */
    public void setAddressUpdate(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>geoly.USER.ADDRESS_UPDATE</code>.
     */
    public Timestamp getAddressUpdate() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>geoly.USER.CREATED_AT</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>geoly.USER.CREATED_AT</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>geoly.USER.EMAIL</code>.
     */
    public void setEmail(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>geoly.USER.EMAIL</code>.
     */
    public String getEmail() {
        return (String) get(6);
    }

    /**
     * Setter for <code>geoly.USER.NICK_NAME</code>.
     */
    public void setNickName(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>geoly.USER.NICK_NAME</code>.
     */
    public String getNickName() {
        return (String) get(7);
    }

    /**
     * Setter for <code>geoly.USER.PASSWORD</code>.
     */
    public void setPassword(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>geoly.USER.PASSWORD</code>.
     */
    public String getPassword() {
        return (String) get(8);
    }

    /**
     * Setter for <code>geoly.USER.PROFILE_IMAGE_URL</code>.
     */
    public void setProfileImageUrl(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>geoly.USER.PROFILE_IMAGE_URL</code>.
     */
    public String getProfileImageUrl() {
        return (String) get(9);
    }

    /**
     * Setter for <code>geoly.USER.VERIFIED</code>.
     */
    public void setVerified(Byte value) {
        set(10, value);
    }

    /**
     * Getter for <code>geoly.USER.VERIFIED</code>.
     */
    public Byte getVerified() {
        return (Byte) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Integer, String, Byte, String, Timestamp, Timestamp, String, String, String, String, Byte> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Integer, String, Byte, String, Timestamp, Timestamp, String, String, String, String, Byte> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return User.USER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return User.USER.ABOUT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field3() {
        return User.USER.ACTIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return User.USER.ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return User.USER.ADDRESS_UPDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return User.USER.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return User.USER.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return User.USER.NICK_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return User.USER.PASSWORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return User.USER.PROFILE_IMAGE_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field11() {
        return User.USER.VERIFIED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getAbout();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component3() {
        return getActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getAddressUpdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getNickName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getProfileImageUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component11() {
        return getVerified();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getAbout();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value3() {
        return getActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getAddressUpdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getNickName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getProfileImageUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value11() {
        return getVerified();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value2(String value) {
        setAbout(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value3(Byte value) {
        setActive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value4(String value) {
        setAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value5(Timestamp value) {
        setAddressUpdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value6(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value7(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value8(String value) {
        setNickName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value9(String value) {
        setPassword(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value10(String value) {
        setProfileImageUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value11(Byte value) {
        setVerified(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord values(Integer value1, String value2, Byte value3, String value4, Timestamp value5, Timestamp value6, String value7, String value8, String value9, String value10, Byte value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRecord
     */
    public UserRecord() {
        super(User.USER);
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(Integer id, String about, Byte active, String address, Timestamp addressUpdate, Timestamp createdAt, String email, String nickName, String password, String profileImageUrl, Byte verified) {
        super(User.USER);

        set(0, id);
        set(1, about);
        set(2, active);
        set(3, address);
        set(4, addressUpdate);
        set(5, createdAt);
        set(6, email);
        set(7, nickName);
        set(8, password);
        set(9, profileImageUrl);
        set(10, verified);
    }
}
