services:
  backend:
    image: geoly-backend
    container_name: geoly-backend
    ports:
    - '8080:8080'
  frontend:
    container_name: geoly-frontend
    image: geoly-frontend
    stdin_open: true
    ports:
    - "3000:3000"