services:
  traefik:
    image: traefik:v2.0
    container_name: traefik
    restart: always
    ports:
      - 8080:8080
      - 80:80
      - 443:443
      - 8443:8443
    command:
      - --api.insecure=false
      - --api.dashboard=false
      - --api.debug=false
      ## Log Settings (options: ERROR, DEBUG, PANIC, FATAL, WARN, INFO) - https://docs.traefik.io/observability/logs/ ##
      - --log.level=ERROR
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.file.filename=/dynamic.yaml
      - --providers.docker.network=web
      ## Entrypoints Settings
      - --entrypoints.frontend.address=:80
      - --entrypoints.frontend-secured.address=:443
      - --entrypoints.backend.address=:8081
      - --entrypoints.backend-secured.address=:8443
      ## Certificate Settings (Let's Encrypt)
      - --certificatesresolvers.mytlschallenge.acme.tlschallenge=true
      - --certificatesresolvers.mytlschallenge.acme.email=info@geoly.com
      - --certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json
    volumes:
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dynamic.yaml:/dynamic.yaml
    networks:
    - web
    labels:
    - traefik.enable=true
    - traefik.http.routers.api.rule=Host(`monitor.geoly.tk`)
    - traefik.http.routers.api.service=api@internal

  frontend:
    image: dusan7991/geoly-frontend
    container_name: geoly-frontend
    depends_on:
      - traefik
    stdin_open: true
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.rule=HostRegexp(`{host:(www.)?geoly.tk}`)
      - traefik.http.routers.frontend.entrypoints=frontend
      - traefik.http.routers.frontend.middlewares=redirect@file
      - traefik.http.routers.frontend-secured.rule=HostRegexp(`{host:(www.)?geoly.tk}`)
      - traefik.http.routers.frontend-secured.entrypoints=frontend-secured
      - traefik.http.routers.frontend-secured.tls.certresolver=mytlschallenge
    networks:
      - web

  backend:
    image: dusan7991/geoly-backend
    container_name: geoly-backend
    depends_on:
      - traefik
    restart: always
    expose:
      - 8081
    labels:
      - traefik.enable=true
      - traefik.port=8081
      - traefik.http.routers.backend.rule=HostRegexp(`{host:(www.)?geoly.tk}`)
      - traefik.http.routers.backend.entrypoints=backend
      - traefik.http.routers.backend.middlewares=redirect@file
      - traefik.http.routers.backend-secured.rule=HostRegexp(`{host:(www.)?geoly.tk}`)
      - traefik.http.routers.backend-secured.entrypoints=backend-secured
      - traefik.http.routers.backend-secured.tls.certresolver=mytlschallenge
      - traefik.http.services.backend.loadbalancer.server.port=8081
    networks:
      - web

networks:
  web:
    external: true