package com.geoly.app.models;

public enum LogType {
    ALL,
    REMOVE_BADGE,
    REMOVE_REVIEW,
    REMOVE_PROFILE_IMAGE,
    USER_UPDATE,
    QUEST_UPDATE,
    SOLVE_REPORT,
    KICK_USER_FROM_GROUP,
    REMOVE_QUEST_FROM_GROUP,
    ROLES_UPDATE,
    ADD_QUEST,
    UPDATE_IMAGES
}
