/*
 * This file is generated by jOOQ.
 */
package com.geoly.app.jooq.tables;


import com.geoly.app.jooq.Geoly;
import com.geoly.app.jooq.Indexes;
import com.geoly.app.jooq.Keys;
import com.geoly.app.jooq.tables.records.BadgeRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Badge extends TableImpl<BadgeRecord> {

    private static final long serialVersionUID = 572042341;

    /**
     * The reference instance of <code>geoly.BADGE</code>
     */
    public static final Badge BADGE = new Badge();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BadgeRecord> getRecordType() {
        return BadgeRecord.class;
    }

    /**
     * The column <code>geoly.BADGE.ID</code>.
     */
    public final TableField<BadgeRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>geoly.BADGE.IMAGE_URL</code>.
     */
    public final TableField<BadgeRecord, String> IMAGE_URL = createField("IMAGE_URL", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>geoly.BADGE.NAME</code>.
     */
    public final TableField<BadgeRecord, String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR(20), this, "");

    /**
     * Create a <code>geoly.BADGE</code> table reference
     */
    public Badge() {
        this(DSL.name("BADGE"), null);
    }

    /**
     * Create an aliased <code>geoly.BADGE</code> table reference
     */
    public Badge(String alias) {
        this(DSL.name(alias), BADGE);
    }

    /**
     * Create an aliased <code>geoly.BADGE</code> table reference
     */
    public Badge(Name alias) {
        this(alias, BADGE);
    }

    private Badge(Name alias, Table<BadgeRecord> aliased) {
        this(alias, aliased, null);
    }

    private Badge(Name alias, Table<BadgeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Badge(Table<O> child, ForeignKey<O, BadgeRecord> key) {
        super(child, key, BADGE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Geoly.GEOLY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PRIMARY_KEY_3);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<BadgeRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_3;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<BadgeRecord>> getKeys() {
        return Arrays.<UniqueKey<BadgeRecord>>asList(Keys.CONSTRAINT_3);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Badge as(String alias) {
        return new Badge(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Badge as(Name alias) {
        return new Badge(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Badge rename(String name) {
        return new Badge(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Badge rename(Name name) {
        return new Badge(name, null);
    }
}
