/*
 * This file is generated by jOOQ.
 */
package com.geoly.app.jooq.tables;


import com.geoly.app.jooq.Geoly;
import com.geoly.app.jooq.Indexes;
import com.geoly.app.jooq.Keys;
import com.geoly.app.jooq.tables.records.PointRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Point extends TableImpl<PointRecord> {

    private static final long serialVersionUID = -567154510;

    /**
     * The reference instance of <code>geoly.POINT</code>
     */
    public static final Point POINT = new Point();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PointRecord> getRecordType() {
        return PointRecord.class;
    }

    /**
     * The column <code>geoly.POINT.ID</code>.
     */
    public final TableField<PointRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>geoly.POINT.AMOUNT</code>.
     */
    public final TableField<PointRecord, Integer> AMOUNT = createField("AMOUNT", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>geoly.POINT.CREATED_AT</code>.
     */
    public final TableField<PointRecord, Timestamp> CREATED_AT = createField("CREATED_AT", org.jooq.impl.SQLDataType.TIMESTAMP.precision(6), this, "");

    /**
     * The column <code>geoly.POINT.USER_ID</code>.
     */
    public final TableField<PointRecord, Integer> USER_ID = createField("USER_ID", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>geoly.POINT</code> table reference
     */
    public Point() {
        this(DSL.name("POINT"), null);
    }

    /**
     * Create an aliased <code>geoly.POINT</code> table reference
     */
    public Point(String alias) {
        this(DSL.name(alias), POINT);
    }

    /**
     * Create an aliased <code>geoly.POINT</code> table reference
     */
    public Point(Name alias) {
        this(alias, POINT);
    }

    private Point(Name alias, Table<PointRecord> aliased) {
        this(alias, aliased, null);
    }

    private Point(Name alias, Table<PointRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Point(Table<O> child, ForeignKey<O, PointRecord> key) {
        super(child, key, POINT);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Geoly.GEOLY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.FKR653LUQTDPVNME1QEHLR753IF_INDEX_4, Indexes.PRIMARY_KEY_48C);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PointRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_48C;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PointRecord>> getKeys() {
        return Arrays.<UniqueKey<PointRecord>>asList(Keys.CONSTRAINT_48C);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<PointRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<PointRecord, ?>>asList(Keys.FKR653LUQTDPVNME1QEHLR753IF);
    }

    public User user() {
        return new User(this, Keys.FKR653LUQTDPVNME1QEHLR753IF);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Point as(String alias) {
        return new Point(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Point as(Name alias) {
        return new Point(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Point rename(String name) {
        return new Point(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Point rename(Name name) {
        return new Point(name, null);
    }
}
